import { PricingPlan, Coupon, Subscription } from '@/types/payment';

export const CORE_PRICING_PLANS: PricingPlan[] = [
  {
    id: 'plan-website',
    slug: 'website-development',
    name: 'Website Development',
    category: 'Website',
    startingPriceInr: 24999,
    currency: 'INR',
    billingType: 'ONE_TIME',
    popular: false,
    tagline: 'High-Performance Next.js Business Flagship',
    recommendedFor: 'Startups, Agencies & Growing Brands looking for speed and conversions',
    estimatedScope: '5 to 10 bespoke pages, responsive UI, headless CMS integration, SEO optimization & 100/100 Core Web Vitals.',
    typicalDuration: '2 to 4 Weeks',
    depositPercentage: 50,
    deliverables: [
      'Bespoke Next.js 15+ & Tailwind CSS Design (Zero templates)',
      'Headless Content Management System (Sanity / Strapi / MDX)',
      'Full SEO Schema Markup & Lighthouse 95+ Performance',
      'Contact Forms with Lead Capture & Email Automations',
      'Complete Git Repository Handover & CI/CD Deployment',
      '30-Day Post-Launch Bug Warranty',
    ],
    features: [
      'Next.js App Router Architecture',
      '100% Mobile & Tablet Responsive',
      'WCAG AA Accessibility Compliant',
      'Custom Domain & SSL Provisioning',
      'Interactive Micro-Animations',
      'Google Analytics & Search Console Setup',
    ],
    includedArchitecture: ['Next.js 15', 'TypeScript', 'Tailwind CSS', 'Vercel / Cloud Run', 'Resend / Nodemailer'],
  },
  {
    id: 'plan-ecommerce',
    slug: 'ecommerce-development',
    name: 'E-Commerce Development',
    category: 'E-Commerce',
    startingPriceInr: 49999,
    currency: 'INR',
    billingType: 'ONE_TIME',
    popular: true,
    tagline: 'Custom Multi-Vendor / Direct-to-Consumer Store',
    recommendedFor: 'D2C Brands, Retailers & Digital Product Sellers seeking fast checkout',
    estimatedScope: 'Product catalogs, cart & checkout, payment gateway integration (Razorpay / Stripe), inventory sync, order management portal.',
    typicalDuration: '4 to 6 Weeks',
    depositPercentage: 50,
    deliverables: [
      'Full-Stack Storefront with Instant Product Filtering & Search',
      'Integrated Razorpay / Stripe Checkout with Webhook Reconciliation',
      'Admin Dashboard for Orders, Stock, Customers & Discounts',
      'Automated Invoicing & WhatsApp / Email Order Status Updates',
      'Database Modeling for SKUs, Variants & Inventory Ledger',
      '45-Day Post-Launch Support & Training',
    ],
    features: [
      'Sub-second Page Load Speed',
      'Zero Transaction Surcharge (You own the platform)',
      'Abandoned Cart Recovery Email Flows',
      'Multi-Currency & Tax Calculation Engine',
      'Secure User Authentication & Profile History',
      'Automated PDF Invoice Generation',
    ],
    includedArchitecture: ['Next.js App Router', 'PostgreSQL / Prisma', 'Razorpay SDK', 'Redis Caching', 'Cloudinary / S3'],
  },
  {
    id: 'plan-mobile-app',
    slug: 'mobile-app-development',
    name: 'Mobile App Development',
    category: 'Mobile App',
    startingPriceInr: 79999,
    currency: 'INR',
    billingType: 'ONE_TIME',
    popular: false,
    tagline: 'Native Performance iOS & Android Cross-Platform App',
    recommendedFor: 'Startups and Businesses requiring rich mobile user engagement',
    estimatedScope: 'Cross-platform React Native / Flutter codebase, backend REST/GraphQL APIs, push notifications, offline syncing, app store submission.',
    typicalDuration: '6 to 8 Weeks',
    depositPercentage: 50,
    deliverables: [
      'Unified React Native (Expo) Codebase for iOS & Android',
      'Secure Backend API Architecture with JWT Authentication',
      'Apple App Store & Google Play Store Submission Assistance',
      'Firebase Cloud Messaging (FCM) Push Notifications',
      'Biometric Sign-In (FaceID / Fingerprint) & Offline Mode',
      '60-Day Post-Launch SLA Warranty',
    ],
    features: [
      '60fps Fluid UI Navigation',
      'In-App Purchases & Payment Gateway Support',
      'Real-Time WebSockets / Push Triggers',
      'Deep Linking & Universal App Links',
      'Device Camera, Location & Storage Integration',
      'Crashlytics & Sentry Telemetry Setup',
    ],
    includedArchitecture: ['React Native / Expo', 'Node.js / Express', 'PostgreSQL', 'Firebase Auth / FCM', 'Fastlane'],
  },
  {
    id: 'plan-ai-automation',
    slug: 'ai-and-automation',
    name: 'AI & Automation Solutions',
    category: 'AI & Automation',
    startingPriceInr: 64999,
    currency: 'INR',
    billingType: 'ONE_TIME',
    popular: false,
    tagline: 'Custom LLM Copilots, RAG Pipelines & Workflow Engines',
    recommendedFor: 'Companies seeking AI-driven productivity, smart bots & document analysis',
    estimatedScope: 'Domain-specific Retrieval Augmented Generation (RAG), vector databases (pgvector/Pinecone), LLM streaming UI, background job workers.',
    typicalDuration: '4 to 7 Weeks',
    depositPercentage: 50,
    deliverables: [
      'Domain-Grounding Knowledge Base with Vector Search & Embeddings',
      'Real-Time Streaming Chat Copilot & Multi-Modal Processing',
      'Automated Data Extraction & CRM / ERP Sync Pipelines',
      'Cost-Capped Token Monitoring & Strict Guardrails Engine',
      'Private Serverless LLM Hosting or Cloud API Integration',
      'Architecture Blueprint & Prompt Engineering Handbook',
    ],
    features: [
      'Gemini 2.5 / OpenAI GPT-4o / Claude Integration',
      'Hybrid Semantic & Full-Text Search',
      'Document Parsing (PDF, Excel, Word, CSV)',
      'Enterprise Access Control (RBAC)',
      'Audit Logs & Hallucination Prevention Filters',
      'Scheduled Workflow Automations',
    ],
    includedArchitecture: ['Gemini API SDK', 'pgvector / Supabase', 'LangChain / Vercel AI SDK', 'BullMQ / Redis', 'Next.js 15'],
  },
  {
    id: 'plan-enterprise',
    slug: 'custom-enterprise-solutions',
    name: 'Custom Enterprise Solutions',
    category: 'Custom Enterprise',
    startingPriceInr: 149999,
    currency: 'INR',
    billingType: 'ONE_TIME',
    popular: false,
    tagline: 'Mission-Critical SaaS, Cloud Systems & Internal Tooling',
    recommendedFor: 'Enterprise clients requiring high scalability, compliance & custom workflows',
    estimatedScope: 'Microservices / Modular Monolith, multi-tenant architecture, complex relational schemas, audit trails, legacy software modernization.',
    typicalDuration: '8 to 14 Weeks',
    depositPercentage: 40,
    deliverables: [
      'End-to-End Enterprise Architecture & Database Schema Design',
      'Multi-Tenant SaaS Foundation with Role-Based Access Control',
      'Third-Party Integration Suite (SAP, Salesforce, QuickBooks, Stripe)',
      'Automated Unit, Integration & End-to-End Test Suite',
      'SOC2 / GDPR Alignment & OWASP Security Audit Report',
      '90-Day Priority Enterprise Support & Dedicated Tech Lead',
    ],
    features: [
      'High-Availability Load Balanced Infrastructure',
      'Database Partitioning & Read Replicas',
      'Granular Event Sourcing & Audit Logging',
      'Custom Analytics & Executive Reporting Dashboards',
      'Zero-Downtime Blue/Green Deployments',
      'Full Source Code & Infrastructure-as-Code (Terraform/Docker)',
    ],
    includedArchitecture: ['Next.js Enterprise', 'PostgreSQL / Cloud SQL', 'Docker / Kubernetes', 'Redis Cluster', 'Prisma ORM'],
  },
];

export const RECURRING_AMC_PLANS: PricingPlan[] = [
  {
    id: 'amc-standard',
    slug: 'standard-amc',
    name: 'Website Maintenance & Security AMC',
    category: 'Maintenance & AMC',
    startingPriceInr: 7999,
    currency: 'INR',
    billingType: 'MONTHLY',
    popular: false,
    tagline: 'Continuous Uptime, Security Patches & Health Checks',
    recommendedFor: 'Live websites and portals requiring steady uptime and peace of mind',
    estimatedScope: 'Weekly dependency upgrades, automated daily backups, 24/7 uptime monitoring, security vulnerability patches, 5 hours monthly development.',
    typicalDuration: 'Monthly / Annual Contract',
    depositPercentage: 100,
    deliverables: [
      '24/7 Automated Uptime & SSL Monitoring',
      'Daily Automated Offsite Database & File Backups',
      'Security Patching & Framework Dependency Updates',
      '5 Hours Dedicated Monthly Feature & Content Tweaks',
      'Monthly Performance & Analytics Health Report',
      'Priority Email & Slack Channel Support',
    ],
    features: [
      '99.9% Uptime Guarantee SLA',
      'Emergency Incident Response (< 4 hours)',
      'SEO Health Audits & Broken Link Fixes',
      'Database Vacuuming & Index Optimization',
      'Rollover Hours (Up to 10 hours)',
    ],
    includedArchitecture: ['Sentry Monitoring', 'UptimeRobot', 'Automated GitHub Actions', 'AWS S3 Backups'],
  },
  {
    id: 'amc-cloud-devops',
    slug: 'cloud-hosting-devops',
    name: 'Cloud Hosting & DevOps Support',
    category: 'Maintenance & AMC',
    startingPriceInr: 14999,
    currency: 'INR',
    billingType: 'MONTHLY',
    popular: true,
    tagline: 'Cloud Infrastructure Management & Scaling',
    recommendedFor: 'Growing applications with cloud databases, background jobs and high traffic',
    estimatedScope: 'AWS / GCP / Cloud Run infrastructure oversight, container management, CI/CD pipeline maintenance, database tuning, 10 hours monthly engineering.',
    typicalDuration: 'Monthly / Annual Contract',
    depositPercentage: 100,
    deliverables: [
      'Cloud Architecture Management (GCP, AWS, Vercel, Supabase)',
      'CI/CD Pipeline Automation & Build Optimization',
      'Database Performance Tuning & Read-Replica Monitoring',
      '10 Hours Monthly DevOps & Infrastructure Engineering',
      'Cost Optimization Audits (Reducing monthly cloud bills)',
      '1-Hour Critical Incident Response SLA',
    ],
    features: [
      'Auto-Scaling & Load Balancing Tuning',
      'SSL & DNS Routing Management (Cloudflare)',
      'Disaster Recovery Failover Drills',
      'Docker Container Registry Auditing',
      'Dedicated Slack / WhatsApp VIP Hotline',
    ],
    includedArchitecture: ['Terraform', 'Docker', 'Google Cloud Platform', 'AWS', 'Cloudflare'],
  },
  {
    id: 'amc-dedicated-retainer',
    slug: 'dedicated-engineering-retainer',
    name: 'Dedicated Engineering Retainer (40h/mo)',
    category: 'Maintenance & AMC',
    startingPriceInr: 44999,
    currency: 'INR',
    billingType: 'MONTHLY',
    popular: false,
    tagline: 'Your Fractional Senior Tech Team on Demand',
    recommendedFor: 'Funded startups & enterprises needing continuous sprint execution',
    estimatedScope: '40 dedicated hours per month of senior full-stack development, code reviews, feature rollouts, bi-weekly demo sprints, and strategic roadmap consulting.',
    typicalDuration: 'Monthly Sprint Commitment',
    depositPercentage: 100,
    deliverables: [
      '40 Dedicated Hours / Month of Senior Engineering',
      'Direct Senior Architect Assignment & Daily Standup Sync',
      'Continuous Feature Development & Backlog Execution',
      'Bi-Weekly Sprint Releases & Staging Previews',
      'Architecture Advisory & Technical Hiring Guidance',
      'Zero Overhead (No payroll taxes, benefits, or equipment costs)',
    ],
    features: [
      'Full-Stack TypeScript, React, Next.js, Node.js, Python',
      'Guaranteed Sprint Capacity',
      'Transparent Time-Tracking Logs',
      'Priority Turnaround (24h response)',
      'Direct GitHub Pull Request Workflows',
    ],
    includedArchitecture: ['Full Next.js Ecosystem', 'Prisma', 'React Native', 'PostgreSQL', 'Gemini AI'],
  },
];

export const PROMO_COUPONS: Coupon[] = [
  {
    id: 'cpn-welcome10',
    code: 'WELCOME10',
    discountType: 'PERCENTAGE',
    discountValue: 10,
    minOrderValue: 20000,
    maxDiscount: 15000,
    expiresAt: '2026-12-31T23:59:59Z',
    usageLimit: 100,
    usedCount: 14,
    isActive: true,
    description: '10% Launch Discount on any project plan (Up to ₹15,000 off)',
  },
  {
    id: 'cpn-earlybird',
    code: 'EARLYBIRD',
    discountType: 'FIXED',
    discountValue: 5000,
    minOrderValue: 45000,
    expiresAt: '2026-12-31T23:59:59Z',
    usageLimit: 50,
    usedCount: 9,
    isActive: true,
    description: '₹5,000 Instant Discount on E-Commerce, Mobile App or AI plans',
  },
  {
    id: 'cpn-enterprise20',
    code: 'ENTERPRISE20',
    discountType: 'PERCENTAGE',
    discountValue: 20,
    minOrderValue: 100000,
    maxDiscount: 40000,
    expiresAt: '2026-12-31T23:59:59Z',
    usageLimit: 20,
    usedCount: 3,
    isActive: true,
    description: '20% Special Enterprise Incentive (Up to ₹40,000 off)',
  },
  {
    id: 'cpn-amcstart',
    code: 'AMCSTART',
    discountType: 'FIXED',
    discountValue: 2000,
    minOrderValue: 7000,
    expiresAt: '2026-12-31T23:59:59Z',
    usageLimit: 200,
    usedCount: 22,
    isActive: true,
    description: '₹2,000 Discount on first month or annual AMC engagement',
  },
];

export const DEMO_SAMPLE_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 'sub-brc-8901',
    customerId: 'cust-demo-1',
    customerName: 'Aarav Sharma',
    customerEmail: 'aarav@apexlogistics.in',
    planId: 'amc-standard',
    serviceName: 'Website Maintenance & Security AMC',
    billingCycle: 'MONTHLY',
    amountInr: 7999,
    currency: 'INR',
    status: 'ACTIVE',
    currentPeriodStart: '2026-08-01T00:00:00Z',
    currentPeriodEnd: '2026-08-31T23:59:59Z',
    nextRenewalDate: '2026-09-01T00:00:00Z',
    autoRenew: true,
    gracePeriodDays: 5,
    lastPaymentDate: '2026-08-01T10:15:00Z',
    lastRazorpayPaymentId: 'pay_demo_890123',
    createdAt: '2026-05-01T00:00:00Z',
    updatedAt: '2026-08-01T10:15:00Z',
  },
  {
    id: 'sub-brc-8902',
    customerId: 'cust-demo-2',
    customerName: 'Priya Mehra',
    customerEmail: 'priya@zenithretail.com',
    planId: 'amc-cloud-devops',
    serviceName: 'Cloud Hosting & DevOps Support',
    billingCycle: 'MONTHLY',
    amountInr: 14999,
    currency: 'INR',
    status: 'ACTIVE',
    currentPeriodStart: '2026-08-15T00:00:00Z',
    currentPeriodEnd: '2026-09-14T23:59:59Z',
    nextRenewalDate: '2026-09-15T00:00:00Z',
    autoRenew: true,
    gracePeriodDays: 5,
    lastPaymentDate: '2026-08-15T14:30:00Z',
    lastRazorpayPaymentId: 'pay_demo_890124',
    createdAt: '2026-06-15T00:00:00Z',
    updatedAt: '2026-08-15T14:30:00Z',
  },
];
