import { PricingPlan, Coupon, Subscription, PricingMarket } from '@/types/payment';

export interface DualMarketPricingConfig {
  india: PricingPlan[];
  international: PricingPlan[];
}

export type PricingCategory =
  | 'Web Development'
  | 'E-Commerce'
  | 'Mobile App'
  | 'AI & Automation'
  | 'SaaS / Web Application';

export const PRICING_CATEGORIES: PricingCategory[] = [
  'Web Development',
  'E-Commerce',
  'Mobile App',
  'AI & Automation',
  'SaaS / Web Application',
];

export const DUAL_MARKET_CORE_PLANS: DualMarketPricingConfig = {
  india: [
    // ==========================================
    // 1. WEB DEVELOPMENT
    // ==========================================
    {
      id: 'plan-webdev-basic-in',
      slug: 'web-development-basic',
      name: 'Basic',
      category: 'Web Development',
      market: 'india',
      startingPrice: 29999,
      startingPriceInr: 29999,
      startingPriceUsd: 400,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'ONE_TIME',
      popular: false,
      tagline: 'Personal brands, freelancers & small businesses',
      bestFor: 'Personal brands, freelancers & small businesses',
      targetAudience: 'Personal brands, freelancers & small businesses',
      recommendedFor: 'Founders, freelancers and small local businesses wanting a high-converting digital storefront',
      estimatedScope: 'Up to 5 pages, responsive mobile-first UI/UX, contact & WhatsApp lead capture, analytics and SSL.',
      typicalDuration: '1 to 2 Weeks',
      supportDuration: '30 days support',
      ctaLabel: 'Get Started',
      depositPercentage: 50,
      features: [
        'Up to 5 pages',
        'Responsive mobile-first design',
        'Modern UI/UX',
        'Contact & enquiry forms',
        'WhatsApp integration',
        'Basic SEO setup',
        'Social media integration',
        'Google Maps integration',
        'SSL & security configuration',
        'Basic performance optimization',
        'Analytics integration',
        '1 revision cycle',
        '30 days support',
      ],
      deliverables: [
        'Up to 5 Custom Responsive Pages',
        'Mobile-First Ergonomic UX & Navigation',
        'Integrated Contact & Lead Capture Forms',
        'WhatsApp Business Direct Routing',
        'Google Analytics & SSL Provisioning',
        '30 Days Post-Launch Support',
      ],
      includedArchitecture: ['Next.js 15', 'Tailwind CSS', 'TypeScript', 'Vercel / Cloud Run'],
    },
    {
      id: 'plan-webdev-standard-in',
      slug: 'web-development-standard',
      name: 'Standard',
      category: 'Web Development',
      market: 'india',
      startingPrice: 99999,
      startingPriceInr: 99999,
      startingPriceUsd: 1350,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'ONE_TIME',
      popular: true,
      badgeText: 'MOST POPULAR',
      tagline: 'Growing businesses & professional brands',
      bestFor: 'Growing businesses & professional brands',
      targetAudience: 'Growing businesses & professional brands',
      recommendedFor: 'Growing businesses requiring CMS content management, advanced SEO rankings, and high conversion velocity',
      estimatedScope: 'Up to 12 pages, custom UI/UX design, CMS integration, blog/news module, and Core Web Vitals optimization.',
      typicalDuration: '3 to 4 Weeks',
      supportDuration: '60 days support',
      ctaLabel: 'Get Started',
      depositPercentage: 50,
      features: [
        'Up to 12 pages',
        'Custom UI/UX design',
        'CMS / content management',
        'Advanced contact & lead forms',
        'WhatsApp & social integrations',
        'Advanced on-page SEO',
        'Google Analytics & Search Console',
        'Blog / news module',
        'Speed & Core Web Vitals optimization',
        'Schema markup',
        'Newsletter integration',
        'Conversion-focused sections',
        '2 revision cycles',
        '60 days support',
      ],
      deliverables: [
        'Up to 12 Bespoke Tailored Pages',
        'Headless CMS for Non-Tech Team Content Updates',
        'Comprehensive On-Page SEO & Schema Markup',
        'Blog / News & Publishing Engine',
        'Google Analytics 4 & Search Console Setup',
        '60 Days Post-Launch Technical Support',
      ],
      includedArchitecture: ['Next.js 15 App Router', 'Sanity / Strapi CMS', 'Tailwind CSS', 'Cloudflare CDN'],
    },
    {
      id: 'plan-webdev-advanced-in',
      slug: 'web-development-advanced',
      name: 'Advanced',
      category: 'Web Development',
      market: 'india',
      startingPrice: 249999,
      startingPriceInr: 249999,
      startingPriceUsd: 3350,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'ONE_TIME',
      popular: false,
      tagline: 'Established businesses & complex digital websites',
      bestFor: 'Established businesses & complex digital websites',
      targetAudience: 'Established businesses & complex digital websites',
      recommendedFor: 'Established brands needing bespoke dashboards, client portals, search/filter catalogs, and API backends',
      estimatedScope: 'Up to 25 pages / flexible architecture, user authentication, custom dashboards, database, and API integrations.',
      typicalDuration: '4 to 6 Weeks',
      supportDuration: '90 days support',
      ctaLabel: 'Get a Quote',
      depositPercentage: 50,
      features: [
        'Up to 25 pages / flexible architecture',
        'Fully custom UI/UX',
        'Advanced CMS',
        'User authentication',
        'Custom dashboards',
        'API integrations',
        'Third-party service integrations',
        'Advanced SEO architecture',
        'Dynamic content management',
        'Search & filtering',
        'Database integration',
        'Performance optimization',
        'Security hardening',
        'Analytics & conversion tracking',
        'Deployment & production configuration',
        '90 days support',
      ],
      deliverables: [
        'Up to 25 Pages with Flexible Architecture',
        'User Authentication & Protected Client Dashboard',
        'Custom Database & API Integrations',
        'Advanced Search & Multi-Faceted Filtering',
        'Production Deployment & CI/CD Pipeline',
        '90 Days Post-Launch Warranty Support',
      ],
      includedArchitecture: ['Next.js 15', 'PostgreSQL / Prisma', 'NextAuth / Auth.js', 'Tailwind CSS', 'Docker'],
    },
    {
      id: 'plan-webdev-enterprise-in',
      slug: 'web-development-enterprise',
      name: 'Enterprise',
      category: 'Web Development',
      market: 'india',
      startingPrice: 829999,
      startingPriceInr: 829999,
      startingPriceUsd: 11000,
      isStartingFromPlus: true,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'ONE_TIME',
      popular: false,
      tagline: 'Enterprise organizations & large-scale platforms',
      bestFor: 'Enterprise organizations & large-scale platforms',
      targetAudience: 'Enterprise organizations & large-scale platforms',
      recommendedFor: 'Large enterprise platforms demanding custom design systems, RBAC, high-availability architecture, and IaC handover',
      estimatedScope: 'Enterprise architecture, custom design system, multi-role RBAC, real-time services, cloud deployment, and full Git repository handover.',
      typicalDuration: '8 to 12 Weeks',
      supportDuration: '90 days warranty/support',
      ctaLabel: 'Talk to an Expert',
      depositPercentage: 40,
      features: [
        'Enterprise-grade architecture',
        'Custom design system',
        'Advanced admin dashboard',
        'Multi-role / RBAC access',
        'Custom backend services',
        'Multiple API integrations',
        'Real-time functionality',
        'Advanced search & filtering',
        'Scalable database architecture',
        'Cloud deployment',
        'CI/CD pipeline',
        'Security & performance engineering',
        'Monitoring & logging',
        'High-availability architecture',
        'Technical documentation',
        'Git repository handover',
        '90 days warranty/support',
      ],
      deliverables: [
        'Enterprise-Grade System Architecture & Design System',
        'Multi-Role Role-Based Access Control (RBAC) Admin Suite',
        'High-Availability Cloud Architecture & Microservices',
        'Automated CI/CD & Security Hardening Audit',
        'Complete Technical Documentation & Git Handover',
        '90 Days Priority Enterprise Warranty / Support',
      ],
      includedArchitecture: ['Next.js Enterprise', 'PostgreSQL / Cloud SQL', 'Kubernetes / Docker', 'Redis Cluster', 'Terraform'],
    },

    // ==========================================
    // 2. E-COMMERCE
    // ==========================================
    {
      id: 'plan-ecom-starter-in',
      slug: 'ecommerce-starter',
      name: 'Starter',
      category: 'E-Commerce',
      market: 'india',
      startingPrice: 69999,
      startingPriceInr: 69999,
      startingPriceUsd: 950,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'ONE_TIME',
      popular: false,
      tagline: 'Small online stores',
      bestFor: 'Small online stores',
      targetAudience: 'Small online stores',
      recommendedFor: 'Boutique retailers and small merchants launching their initial direct-to-consumer digital storefront',
      estimatedScope: 'Up to 50 products, categories, shopping cart, checkout, payment gateway, and order ledger.',
      typicalDuration: '2 to 3 Weeks',
      supportDuration: '30 days support',
      ctaLabel: 'Get Started',
      depositPercentage: 50,
      features: [
        'Up to 50 products',
        'Responsive storefront',
        'Product catalogue',
        'Product categories',
        'Shopping cart',
        'Checkout',
        'Customer enquiry',
        'Basic payment gateway',
        'Order management',
        'WhatsApp integration',
        'Basic SEO',
        'Analytics',
        'SSL/security setup',
        '30 days support',
      ],
      deliverables: [
        'Responsive Storefront for Up to 50 Products',
        'Shopping Cart & Streamlined Checkout Flow',
        'Razorpay / Payment Gateway Integration',
        'Merchant Order Management Dashboard',
        'WhatsApp Customer Enquiry Button',
        '30 Days Post-Launch Support',
      ],
      includedArchitecture: ['Next.js App Router', 'PostgreSQL', 'Razorpay Gateway', 'Tailwind CSS'],
    },
    {
      id: 'plan-ecom-professional-in',
      slug: 'ecommerce-professional',
      name: 'Professional',
      category: 'E-Commerce',
      market: 'india',
      startingPrice: 149999,
      startingPriceInr: 149999,
      startingPriceUsd: 2000,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'ONE_TIME',
      popular: true,
      badgeText: 'MOST POPULAR',
      tagline: 'Growing online businesses',
      bestFor: 'Growing online businesses',
      targetAudience: 'Growing online businesses',
      recommendedFor: 'Scaling D2C brands requiring product variants, discount engines, inventory alerts, and automated notifications',
      estimatedScope: 'Up to 250 products, custom storefront, variants, wishlist, accounts, coupons, shipping, and WhatsApp alerts.',
      typicalDuration: '4 to 5 Weeks',
      supportDuration: '60 days support',
      ctaLabel: 'Get Started',
      depositPercentage: 50,
      features: [
        'Up to 250 products',
        'Custom storefront UI/UX',
        'Product variants',
        'Wishlist',
        'Customer accounts',
        'Payment gateway integration',
        'Coupon & discount system',
        'Order tracking',
        'Inventory management',
        'Shipping integration',
        'Email notifications',
        'WhatsApp notifications',
        'Advanced SEO',
        'Analytics & conversion tracking',
        '60 days support',
      ],
      deliverables: [
        'Bespoke Storefront for Up to 250 Products & Variants',
        'Customer Account Portal with Order History & Wishlists',
        'Dynamic Coupon, Promo Code & Discount Engine',
        'Automated Email & WhatsApp Transactional Alerts',
        'Shipping & Logistics Tracking Integration',
        '60 Days Post-Launch Technical Support',
      ],
      includedArchitecture: ['Next.js 15', 'Prisma ORM', 'PostgreSQL', 'Razorpay Gateway', 'Resend Email API'],
    },
    {
      id: 'plan-ecom-advanced-in',
      slug: 'ecommerce-advanced',
      name: 'Advanced',
      category: 'E-Commerce',
      market: 'india',
      startingPrice: 349999,
      startingPriceInr: 349999,
      startingPriceUsd: 4650,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'ONE_TIME',
      popular: false,
      tagline: 'Established e-commerce brands',
      bestFor: 'Established e-commerce brands',
      targetAudience: 'Established e-commerce brands',
      recommendedFor: 'High-volume merchants requiring multi-level categories, abandoned cart recovery, GST invoicing, and review systems',
      estimatedScope: '500+ products, multi-level categories, facet search, multiple gateways, abandoned cart recovery, and logistics APIs.',
      typicalDuration: '6 to 8 Weeks',
      supportDuration: '90 days support',
      ctaLabel: 'Get a Quote',
      depositPercentage: 50,
      features: [
        '500+ products',
        'Advanced product management',
        'Multi-level categories',
        'Advanced filters & search',
        'Multiple payment methods',
        'Shipping & logistics APIs',
        'Inventory synchronization',
        'Customer dashboard',
        'Reviews & ratings',
        'Coupon engine',
        'Abandoned cart functionality',
        'Tax/GST-ready pricing logic',
        'Advanced analytics',
        'Marketing integrations',
        'Admin dashboard',
        'Performance optimization',
        'Security hardening',
        '90 days support',
      ],
      deliverables: [
        'High-Capacity Storefront for 500+ Products & Complex Tax Rules',
        'Advanced Facet Search & Multi-Level Category Navigation',
        'Automated Abandoned Cart Email & SMS Recovery Flow',
        'Full Admin Operations, Stock & Logistics Dashboard',
        'Automated GST-Compliant PDF Invoicing Engine',
        '90 Days Post-Launch Engineering Warranty',
      ],
      includedArchitecture: ['Next.js Commerce', 'PostgreSQL / Supabase', 'Redis Caching', 'Razorpay / Stripe', 'Shiprocket API'],
    },
    {
      id: 'plan-ecom-enterprise-in',
      slug: 'ecommerce-enterprise',
      name: 'Enterprise',
      category: 'E-Commerce',
      market: 'india',
      startingPrice: 699999,
      startingPriceInr: 699999,
      startingPriceUsd: 9350,
      isStartingFromPlus: true,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'ONE_TIME',
      popular: false,
      tagline: 'Large-scale e-commerce businesses',
      bestFor: 'Large-scale e-commerce businesses',
      targetAudience: 'Large-scale e-commerce businesses',
      recommendedFor: 'Omnichannel retailers and multi-vendor marketplaces needing ERP/CRM integration, payment orchestration, and cloud scale',
      estimatedScope: 'Large product catalog, custom commerce architecture, multi-vendor, ERP/CRM integration, real-time orders, and cloud deployment.',
      typicalDuration: '8 to 14 Weeks',
      supportDuration: '90 days warranty/support',
      ctaLabel: 'Talk to an Expert',
      depositPercentage: 40,
      features: [
        'Large product catalogue',
        'Custom commerce architecture',
        'Multi-vendor capability',
        'Multi-role administration',
        'Advanced inventory management',
        'ERP/API integration',
        'CRM integration',
        'Payment orchestration',
        'Logistics integrations',
        'Real-time order updates',
        'Advanced customer segmentation',
        'Custom promotions engine',
        'Scalable database',
        'Cloud infrastructure',
        'Monitoring & logging',
        'Security engineering',
        'CI/CD deployment',
        'Technical documentation',
        '90 days warranty/support',
      ],
      deliverables: [
        'Enterprise Custom Commerce & Multi-Vendor Engine',
        'Seamless Integration with ERP (SAP / Zoho / Tally) & CRM',
        'Real-Time Order Orchestration & Logistics Webhooks',
        'Scalable Distributed Database & Microservices Foundation',
        'Complete Source Code, IaC & Technical Architecture Docs',
        '90 Days Priority Enterprise Warranty / Support',
      ],
      includedArchitecture: ['Next.js Enterprise', 'PostgreSQL / Cloud SQL', 'Redis Cluster', 'Docker / Kubernetes', 'Multi-Gateway'],
    },

    // ==========================================
    // 3. MOBILE APP
    // ==========================================
    {
      id: 'plan-mobile-basic-in',
      slug: 'mobile-app-basic',
      name: 'Basic',
      category: 'Mobile App',
      market: 'india',
      startingPrice: 119999,
      startingPriceInr: 119999,
      startingPriceUsd: 1600,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'ONE_TIME',
      popular: false,
      tagline: 'MVPs & simple business apps',
      bestFor: 'MVPs & simple business apps',
      targetAudience: 'MVPs & simple business apps',
      recommendedFor: 'Founders and startups testing mobile app market viability with a polished MVP',
      estimatedScope: 'Android or iOS, up to 5 screens, cross-platform build, onboarding, auth, push notifications, and store guidance.',
      typicalDuration: '3 to 4 Weeks',
      supportDuration: '30 days support',
      ctaLabel: 'Get Started',
      depositPercentage: 50,
      features: [
        'Android or iOS',
        'Up to 5 screens',
        'Cross-platform development',
        'Custom basic UI/UX',
        'User onboarding',
        'Basic authentication',
        'Push notifications',
        'Basic API integration',
        'Contact/help module',
        'Analytics',
        'App build configuration',
        'Play Store / App Store guidance',
        '30 days support',
      ],
      deliverables: [
        'Up to 5 Custom Mobile Screens (Android or iOS)',
        'User Onboarding & Authentication Flow',
        'Firebase Cloud Messaging Push Notifications',
        'REST API Connection & Analytics Telemetry',
        'Store Build Generation & Publishing Guidance',
        '30 Days Post-Launch Technical Support',
      ],
      includedArchitecture: ['React Native / Expo', 'Node.js', 'Firebase Auth', 'Firebase Cloud Messaging'],
    },
    {
      id: 'plan-mobile-standard-in',
      slug: 'mobile-app-standard',
      name: 'Standard',
      category: 'Mobile App',
      market: 'india',
      startingPrice: 249999,
      startingPriceInr: 249999,
      startingPriceUsd: 3350,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'ONE_TIME',
      popular: true,
      badgeText: 'MOST POPULAR',
      tagline: 'Growing businesses & customer-facing apps',
      bestFor: 'Growing businesses & customer-facing apps',
      targetAudience: 'Growing businesses & customer-facing apps',
      recommendedFor: 'Growing businesses requiring dual Android + iOS presence, OTP authentication, payments, and deep linking',
      estimatedScope: 'Android + iOS, up to 15 screens, custom UI/UX, OTP sign-in, user profile, payment gateway, and store deployment assistance.',
      typicalDuration: '5 to 7 Weeks',
      supportDuration: '60 days support',
      ctaLabel: 'Get Started',
      depositPercentage: 50,
      features: [
        'Android + iOS',
        'Up to 15 screens',
        'Custom UI/UX',
        'User registration & login',
        'OTP / authentication',
        'User profile',
        'Push notifications',
        'Payment gateway',
        'REST API integration',
        'Analytics',
        'Deep linking',
        'App navigation architecture',
        'Backend integration',
        'Store deployment assistance',
        '60 days support',
      ],
      deliverables: [
        'Cross-Platform Android & iOS Production Builds (Up to 15 screens)',
        'OTP / SMS Phone Number Verification & User Profiles',
        'Integrated Mobile In-App Payment Gateway',
        'Deep Linking & Universal Link Architecture',
        'Google Play & Apple App Store Deployment Assistance',
        '60 Days Post-Launch SLA Warranty',
      ],
      includedArchitecture: ['React Native / Expo', 'Node.js / Express', 'PostgreSQL', 'Razorpay Mobile SDK', 'Firebase'],
    },
    {
      id: 'plan-mobile-advanced-in',
      slug: 'mobile-app-advanced',
      name: 'Advanced',
      category: 'Mobile App',
      market: 'india',
      startingPrice: 499999,
      startingPriceInr: 499999,
      startingPriceUsd: 6650,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'ONE_TIME',
      popular: false,
      tagline: 'Feature-rich business applications',
      bestFor: 'Feature-rich business applications',
      targetAudience: 'Feature-rich business applications',
      recommendedFor: 'Service platforms requiring live chat, GPS location mapping, offline SQLite sync, and dedicated admin dashboards',
      estimatedScope: 'Android + iOS, 25+ screens, advanced UI/UX, RBAC auth, chat, maps & geolocation, offline sync, and full store deployment.',
      typicalDuration: '8 to 10 Weeks',
      supportDuration: '90 days support',
      ctaLabel: 'Get a Quote',
      depositPercentage: 50,
      features: [
        'Android + iOS',
        '25+ screens',
        'Advanced custom UI/UX',
        'Role-based authentication',
        'Payment integration',
        'Real-time notifications',
        'Chat / messaging',
        'Maps & location services',
        'Advanced API integrations',
        'Offline data support',
        'File/image uploads',
        'Advanced analytics',
        'Admin dashboard',
        'Third-party integrations',
        'Performance optimization',
        'Security hardening',
        'App Store / Play Store deployment',
        '90 days support',
      ],
      deliverables: [
        'Feature-Rich Android & iOS App Suite (25+ Screens)',
        'Real-Time Chat & Instant Push Notification Subsystems',
        'Live Maps, Geolocation & Geofencing Integration',
        'Offline Data Storage & Auto-Sync Engine',
        'Web Admin Management Portal for Operators',
        '90 Days Post-Launch Warranty Support',
      ],
      includedArchitecture: ['React Native / Expo', 'PostgreSQL / Prisma', 'WebSockets / Socket.io', 'Google Maps SDK', 'Sentry'],
    },
    {
      id: 'plan-mobile-enterprise-in',
      slug: 'mobile-app-enterprise',
      name: 'Enterprise',
      category: 'Mobile App',
      market: 'india',
      startingPrice: 829999,
      startingPriceInr: 829999,
      startingPriceUsd: 11000,
      isStartingFromPlus: true,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'ONE_TIME',
      popular: false,
      tagline: 'Enterprise & large-scale mobile platforms',
      bestFor: 'Enterprise & large-scale mobile platforms',
      targetAudience: 'Enterprise & large-scale mobile platforms',
      recommendedFor: 'Mission-critical enterprise mobility platforms with custom native bridges, biometric security, and scalable cloud backends',
      estimatedScope: 'Large-scale app architecture, custom native modules, flexible screens, enterprise auth, telemetry, and complete code handover.',
      typicalDuration: '10 to 16 Weeks',
      supportDuration: '90 days warranty/support',
      ctaLabel: 'Talk to an Expert',
      depositPercentage: 40,
      features: [
        'Android + iOS',
        'Large-scale application architecture',
        'Custom native modules',
        'Flexible screen architecture',
        'Multi-role access control',
        'Real-time synchronization',
        'Advanced offline capabilities',
        'Complex API ecosystem',
        'Enterprise authentication',
        'Payment & transaction systems',
        'Location & geofencing',
        'Advanced notifications',
        'Analytics & monitoring',
        'Scalable backend',
        'Cloud infrastructure',
        'Security engineering',
        'CI/CD pipeline',
        'App performance monitoring',
        'Technical documentation',
        '90 days warranty/support',
      ],
      deliverables: [
        'Enterprise Scalable Mobile Platform for Android & iOS',
        'Custom Native Bridges (Swift / Kotlin) for High Performance',
        'Enterprise Authentication (SSO / Biometrics / OAuth2)',
        'Automated CI/CD Fastlane Build & Release Pipeline',
        'Full Source Code, API Schemas & Architectural Documentation',
        '90 Days Priority Enterprise Warranty / Support',
      ],
      includedArchitecture: ['React Native / Kotlin / Swift', 'Node.js / Go API', 'PostgreSQL Cluster', 'Redis', 'Fastlane CI/CD'],
    },

    // ==========================================
    // 4. AI & AUTOMATION
    // ==========================================
    {
      id: 'plan-ai-starter-in',
      slug: 'ai-automation-starter',
      name: 'Starter',
      category: 'AI & Automation',
      market: 'india',
      startingPrice: 149999,
      startingPriceInr: 149999,
      startingPriceUsd: 2000,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'ONE_TIME',
      popular: false,
      tagline: 'Businesses starting with AI',
      bestFor: 'Businesses starting with AI',
      targetAudience: 'Businesses starting with AI',
      recommendedFor: 'Companies introducing their first AI chatbot, automated FAQ responder, or prompt-engineered content workflow',
      estimatedScope: 'AI chatbot, website assistant, FAQ automation, OpenAI / Gemini integration, prompt engineering, and deployment.',
      typicalDuration: '2 to 3 Weeks',
      supportDuration: '30 days support',
      ctaLabel: 'Get Started',
      depositPercentage: 50,
      features: [
        'AI chatbot',
        'Website AI assistant',
        'FAQ automation',
        'AI-powered content assistance',
        'Basic document processing',
        'OpenAI / compatible AI API integration',
        'Prompt engineering',
        'Basic admin controls',
        'Conversation history',
        'Analytics',
        'Basic security',
        'Deployment',
        '30 days support',
      ],
      deliverables: [
        'Interactive Website AI Chatbot & Assistant',
        'Automated Customer FAQ & Lead Inquiry Capture',
        'Custom Prompt Engineering & Guardrail Configuration',
        'Conversation Logs & Analytics Dashboard',
        'Cloud Deployment & API Key Security Setup',
        '30 Days Post-Launch Technical Support',
      ],
      includedArchitecture: ['Gemini API SDK / OpenAI', 'Next.js 15', 'Tailwind CSS', 'Vercel / Cloud Run'],
    },
    {
      id: 'plan-ai-business-in',
      slug: 'ai-automation-business',
      name: 'Business',
      category: 'AI & Automation',
      market: 'india',
      startingPrice: 299999,
      startingPriceInr: 299999,
      startingPriceUsd: 4000,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'ONE_TIME',
      popular: true,
      badgeText: 'MOST POPULAR',
      tagline: 'Businesses automating customer & internal workflows',
      bestFor: 'Businesses automating customer & internal workflows',
      targetAudience: 'Businesses automating customer & internal workflows',
      recommendedFor: 'Organizations looking to ground AI on proprietary PDF/docs (RAG), automate CRM workflows, and enable WhatsApp/API bots',
      estimatedScope: 'Custom knowledge base, document Q&A, RAG responses, lead qualification, email & CRM automation, human handoff, and usage monitoring.',
      typicalDuration: '4 to 6 Weeks',
      supportDuration: '60 days support',
      ctaLabel: 'Get Started',
      depositPercentage: 50,
      features: [
        'AI chatbot',
        'Custom knowledge base',
        'Document Q&A',
        'RAG-based responses',
        'Lead qualification',
        'AI-powered search',
        'Email automation',
        'Workflow automation',
        'CRM integration',
        'WhatsApp/API integration',
        'Admin dashboard',
        'Conversation analytics',
        'Human handoff',
        'Usage monitoring',
        '60 days support',
      ],
      deliverables: [
        'Domain-Grounded RAG Pipeline with Document Ingestion (PDF / Docs)',
        'Automated Lead Qualification & CRM Sync (HubSpot / Zoho)',
        'WhatsApp & Web Multi-Channel AI Assistant',
        'Operator Human-in-the-Loop Handoff Trigger Subsystem',
        'Token Budgeting, Usage Analytics & Admin Controls',
        '60 Days Post-Launch Technical Support',
      ],
      includedArchitecture: ['Gemini 2.5 / OpenAI', 'pgvector / Supabase', 'Vercel AI SDK', 'BullMQ / Redis', 'WhatsApp API'],
    },
    {
      id: 'plan-ai-advanced-in',
      slug: 'ai-automation-advanced',
      name: 'Advanced',
      category: 'AI & Automation',
      market: 'india',
      startingPrice: 599999,
      startingPriceInr: 599999,
      startingPriceUsd: 8000,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'ONE_TIME',
      popular: false,
      tagline: 'AI-powered business platforms',
      bestFor: 'AI-powered business platforms',
      targetAudience: 'AI-powered business platforms',
      recommendedFor: 'Enterprises automating multi-step workflows with AI agents, semantic vector pipelines, automated reporting, and RBAC',
      estimatedScope: 'Advanced RAG, multiple knowledge sources, ingestion pipeline, semantic/vector search, AI agents, multi-step workflows, and model orchestration.',
      typicalDuration: '6 to 9 Weeks',
      supportDuration: '90 days support',
      ctaLabel: 'Get a Quote',
      depositPercentage: 50,
      features: [
        'Advanced RAG architecture',
        'Multiple knowledge sources',
        'Document ingestion pipeline',
        'Semantic/vector search',
        'AI agents',
        'Multi-step workflows',
        'Custom business logic',
        'CRM/ERP integrations',
        'Automated reporting',
        'AI-powered recommendations',
        'Role-based access',
        'Advanced analytics',
        'Model/API orchestration',
        'Evaluation & testing',
        'Security controls',
        'Cloud deployment',
        '90 days support',
      ],
      deliverables: [
        'Multi-Source Vector Knowledge Base with Automated ETL Pipeline',
        'Autonomous Multi-Step AI Agents for Business Workflows',
        'Automated Executive Insights & PDF Report Generation',
        'Model Orchestration with Fallback & Safety Evaluation Framework',
        'Role-Based Document Access Control (RBAC) & Tenant Security',
        '90 Days Post-Launch Engineering Warranty',
      ],
      includedArchitecture: ['Gemini API SDK', 'pgvector / Pinecone', 'LangChain / Vercel AI', 'FastAPI / Python', 'Next.js 15'],
    },
    {
      id: 'plan-ai-enterprise-in',
      slug: 'ai-automation-enterprise',
      name: 'Enterprise',
      category: 'AI & Automation',
      market: 'india',
      startingPrice: 999999,
      startingPriceInr: 999999,
      startingPriceUsd: 13350,
      isStartingFromPlus: true,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'ONE_TIME',
      popular: false,
      tagline: 'Enterprise AI & automation systems',
      bestFor: 'Enterprise AI & automation systems',
      targetAudience: 'Enterprise AI & automation systems',
      recommendedFor: 'Large organizations deploying multi-agent AI ecosystems, private knowledge data governance, and automated CI/CD evaluation',
      estimatedScope: 'Multi-agent AI architecture, enterprise RAG, private systems, multiple models, CRM/ERP integration, audit logs, and data governance.',
      typicalDuration: '10 to 16 Weeks',
      supportDuration: '90 days warranty/support',
      ctaLabel: 'Talk to an Expert',
      depositPercentage: 40,
      features: [
        'Multi-agent AI architecture',
        'Enterprise RAG',
        'Private knowledge systems',
        'Advanced AI workflows',
        'Custom AI agents',
        'Multiple model integration',
        'Enterprise API ecosystem',
        'CRM / ERP integration',
        'Role-based access',
        'Audit logs',
        'Data governance',
        'Advanced monitoring',
        'AI evaluation framework',
        'Security architecture',
        'Scalable cloud infrastructure',
        'CI/CD',
        'Performance optimization',
        'Technical documentation',
        '90 days warranty/support',
      ],
      deliverables: [
        'Enterprise Multi-Agent AI Orchestration & Private RAG Engine',
        'Comprehensive Data Governance, Strict RBAC & Audit Trails',
        'High-Throughput CRM / ERP Bi-Directional Connectors',
        'Continuous Model Benchmarking & Hallucination Prevention Pipeline',
        'Full Source Code, Deployment Blueprints & AI Engineering Manuals',
        '90 Days Priority Enterprise Warranty / Support',
      ],
      includedArchitecture: ['Multi-LLM Engine', 'pgvector / Qdrant', 'Kubernetes / Cloud Run', 'Redis Streams', 'MLflow'],
    },

    // ==========================================
    // 5. SAAS / WEB APPLICATION
    // ==========================================
    {
      id: 'plan-saas-starter-in',
      slug: 'saas-web-app-starter',
      name: 'Starter',
      category: 'SaaS / Web Application',
      market: 'india',
      startingPrice: 249999,
      startingPriceInr: 249999,
      startingPriceUsd: 3350,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'ONE_TIME',
      popular: false,
      tagline: 'MVPs & early-stage SaaS products',
      bestFor: 'MVPs & early-stage SaaS products',
      targetAudience: 'MVPs & early-stage SaaS products',
      recommendedFor: 'Startup founders building a production-ready SaaS MVP with auth, database CRUD, and user dashboards',
      estimatedScope: 'Responsive web app, custom UI/UX, user auth, dashboard, basic database, CRUD, admin panel, and cloud deployment.',
      typicalDuration: '4 to 6 Weeks',
      supportDuration: '60 days support',
      ctaLabel: 'Get Started',
      depositPercentage: 50,
      features: [
        'Responsive web application',
        'Custom UI/UX',
        'User registration & login',
        'User dashboard',
        'Basic database',
        'CRUD functionality',
        'Basic API architecture',
        'Basic admin panel',
        'Email notifications',
        'Basic analytics',
        'Cloud deployment',
        'SSL/security configuration',
        '60 days support',
      ],
      deliverables: [
        'Full-Stack SaaS Web Application & User Portal',
        'User Registration, Login & Session Management',
        'Relational Database Modeling with CRUD Operations',
        'Operator Admin Panel for User & System Oversight',
        'Production Cloud Deployment & SSL Configuration',
        '60 Days Post-Launch Technical Support',
      ],
      includedArchitecture: ['Next.js 15 App Router', 'PostgreSQL / Prisma', 'NextAuth', 'Tailwind CSS'],
    },
    {
      id: 'plan-saas-professional-in',
      slug: 'saas-web-app-professional',
      name: 'Professional',
      category: 'SaaS / Web Application',
      market: 'india',
      startingPrice: 499999,
      startingPriceInr: 499999,
      startingPriceUsd: 6650,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'ONE_TIME',
      popular: true,
      badgeText: 'MOST POPULAR',
      tagline: 'Growing SaaS products',
      bestFor: 'Growing SaaS products',
      targetAudience: 'Growing SaaS products',
      recommendedFor: 'Growth-stage software platforms needing recurring subscriptions, billing gateways, role access, and API integrations',
      estimatedScope: 'Full-stack web application, design system, user & admin dashboards, RBAC, subscription billing, REST/GraphQL APIs, and security.',
      typicalDuration: '6 to 8 Weeks',
      supportDuration: '90 days support',
      ctaLabel: 'Get Started',
      depositPercentage: 50,
      features: [
        'Full-stack web application',
        'Custom design system',
        'User dashboard',
        'Admin dashboard',
        'Role-based access',
        'Subscription/billing',
        'Payment gateway',
        'REST/GraphQL APIs',
        'Database architecture',
        'Email notifications',
        'Search & filtering',
        'Analytics',
        'Third-party integrations',
        'Cloud deployment',
        'Performance optimization',
        'Security hardening',
        '90 days support',
      ],
      deliverables: [
        'Bespoke Full-Stack SaaS Engine & Custom Design System',
        'Granular Role-Based Access Control (Admin, Manager, Member)',
        'Recurring Subscription Billing & Payment Gateway Integration',
        'REST / GraphQL API Endpoints for Mobile & Third-Party Sync',
        'Comprehensive Analytics & User Telemetry Dashboard',
        '90 Days Post-Launch SLA Warranty',
      ],
      includedArchitecture: ['Next.js 15', 'PostgreSQL / Supabase', 'Razorpay Subscriptions / Stripe', 'Redis Caching', 'Prisma ORM'],
    },
    {
      id: 'plan-saas-advanced-in',
      slug: 'saas-web-app-advanced',
      name: 'Advanced',
      category: 'SaaS / Web Application',
      market: 'india',
      startingPrice: 829999,
      startingPriceInr: 829999,
      startingPriceUsd: 11000,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'ONE_TIME',
      popular: false,
      tagline: 'Complex SaaS & business platforms',
      bestFor: 'Complex SaaS & business platforms',
      targetAudience: 'Complex SaaS & business platforms',
      recommendedFor: 'Scaled SaaS businesses demanding multi-tenant tenancy, workflow engines, real-time sync, and document management',
      estimatedScope: 'Multi-tenant capability, advanced RBAC, subscription engine, API ecosystem, real-time features, workflow engine, and CI/CD.',
      typicalDuration: '8 to 12 Weeks',
      supportDuration: '90 days warranty/support',
      ctaLabel: 'Get a Quote',
      depositPercentage: 50,
      features: [
        'Advanced SaaS architecture',
        'Multi-tenant capability',
        'Advanced RBAC',
        'Subscription management',
        'Payment & billing system',
        'Advanced dashboards',
        'API ecosystem',
        'Real-time features',
        'Notifications',
        'Advanced search',
        'File/document management',
        'Workflow engine',
        'Third-party integrations',
        'Advanced analytics',
        'Database optimization',
        'Cloud infrastructure',
        'CI/CD',
        'Monitoring & logging',
        '90 days warranty/support',
      ],
      deliverables: [
        'Multi-Tenant SaaS Architecture with Isolated Tenant Databases',
        'Automated Workflow Automation & Trigger Rule Engine',
        'Real-Time Collaboration & WebSockets Event System',
        'Secure File/Document Vault with S3 Storage & Encryption',
        'Automated CI/CD Pipeline & Zero-Downtime Deployment',
        '90 Days Post-Launch Warranty Support',
      ],
      includedArchitecture: ['Next.js Enterprise', 'PostgreSQL Cluster', 'Redis Pub/Sub', 'Docker / Kubernetes', 'BullMQ'],
    },
    {
      id: 'plan-saas-enterprise-in',
      slug: 'saas-web-app-enterprise',
      name: 'Enterprise',
      category: 'SaaS / Web Application',
      market: 'india',
      startingPrice: 1499999,
      startingPriceInr: 1499999,
      startingPriceUsd: 20000,
      isStartingFromPlus: true,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'ONE_TIME',
      popular: false,
      tagline: 'Enterprise SaaS & mission-critical platforms',
      bestFor: 'Enterprise SaaS & mission-critical platforms',
      targetAudience: 'Enterprise SaaS & mission-critical platforms',
      recommendedFor: 'Mission-critical enterprise software platforms needing SSO/SAML, multi-region cloud clustering, audit trails, and compliance',
      estimatedScope: 'Enterprise multi-tenant, microservices, enterprise auth, SSO, complex billing, high-scale APIs, multi-region, and disaster recovery.',
      typicalDuration: '12 to 18 Weeks',
      supportDuration: '90 days warranty/support',
      ctaLabel: 'Talk to an Expert',
      depositPercentage: 40,
      features: [
        'Enterprise multi-tenant architecture',
        'Custom microservices / modular architecture',
        'Advanced RBAC & permissions',
        'Enterprise authentication',
        'SSO / OAuth integration',
        'Complex billing & subscription engine',
        'Advanced workflow automation',
        'Real-time systems',
        'High-scale API architecture',
        'Advanced database architecture',
        'Multi-region/cloud-ready architecture',
        'Security & compliance engineering',
        'Audit logging',
        'Monitoring & observability',
        'CI/CD & DevOps',
        'Load/performance engineering',
        'Backup & disaster recovery strategy',
        'Technical architecture documentation',
        'Git repository & deployment handover',
        '90 days warranty/support',
      ],
      deliverables: [
        'Mission-Critical Enterprise Multi-Tenant SaaS Platform',
        'Enterprise SSO / SAML / Okta & Granular RBAC Permissions',
        'Multi-Region Cloud Architecture with Automated Failover',
        'SOC2 / GDPR Alignment & Comprehensive Audit Logging',
        'Full Source Code, IaC Terraform & Architecture Runbooks',
        '90 Days Priority Enterprise Warranty / Support',
      ],
      includedArchitecture: ['Next.js Enterprise', 'Cloud SQL / PostgreSQL', 'Kubernetes / GCP / AWS', 'Kafka / Redis', 'Terraform'],
    },
  ],

  international: [
    // US / Global market mirrored plans for multi-currency toggle
    {
      id: 'plan-webdev-basic-intl',
      slug: 'web-development-basic-intl',
      name: 'Basic',
      category: 'Web Development',
      market: 'international',
      startingPrice: 400,
      startingPriceInr: 29999,
      startingPriceUsd: 400,
      currency: 'USD',
      currencySymbol: '$',
      billingType: 'ONE_TIME',
      popular: false,
      tagline: 'Personal brands, freelancers & small businesses',
      bestFor: 'Personal brands, freelancers & small businesses',
      targetAudience: 'Personal brands, freelancers & small businesses',
      recommendedFor: 'Founders, freelancers and small local businesses wanting a high-converting digital storefront',
      estimatedScope: 'Up to 5 pages, responsive mobile-first UI/UX, contact & WhatsApp lead capture, analytics and SSL.',
      typicalDuration: '1 to 2 Weeks',
      supportDuration: '30 days support',
      ctaLabel: 'Get Started',
      depositPercentage: 50,
      features: [
        'Up to 5 pages',
        'Responsive mobile-first design',
        'Modern UI/UX',
        'Contact & enquiry forms',
        'WhatsApp integration',
        'Basic SEO setup',
        'Social media integration',
        'Google Maps integration',
        'SSL & security configuration',
        'Basic performance optimization',
        'Analytics integration',
        '1 revision cycle',
        '30 days support',
      ],
      deliverables: ['5 Bespoke Responsive Pages', 'Mobile-First Ergonomic UX', 'Analytics & SSL Setup', '30 Days Support'],
      includedArchitecture: ['Next.js 15', 'Tailwind CSS', 'TypeScript', 'Vercel Edge'],
    },
    {
      id: 'plan-webdev-standard-intl',
      slug: 'web-development-standard-intl',
      name: 'Standard',
      category: 'Web Development',
      market: 'international',
      startingPrice: 1350,
      startingPriceInr: 99999,
      startingPriceUsd: 1350,
      currency: 'USD',
      currencySymbol: '$',
      billingType: 'ONE_TIME',
      popular: true,
      badgeText: 'MOST POPULAR',
      tagline: 'Growing businesses & professional brands',
      bestFor: 'Growing businesses & professional brands',
      targetAudience: 'Growing businesses & professional brands',
      recommendedFor: 'Growing businesses requiring CMS content management, advanced SEO rankings, and high conversion velocity',
      estimatedScope: 'Up to 12 pages, custom UI/UX design, CMS integration, blog/news module, and Core Web Vitals optimization.',
      typicalDuration: '3 to 4 Weeks',
      supportDuration: '60 days support',
      ctaLabel: 'Get Started',
      depositPercentage: 50,
      features: [
        'Up to 12 pages',
        'Custom UI/UX design',
        'CMS / content management',
        'Advanced contact & lead forms',
        'WhatsApp & social integrations',
        'Advanced on-page SEO',
        'Google Analytics & Search Console',
        'Blog / news module',
        'Speed & Core Web Vitals optimization',
        'Schema markup',
        'Newsletter integration',
        'Conversion-focused sections',
        '2 revision cycles',
        '60 days support',
      ],
      deliverables: ['12 Custom Pages', 'Headless CMS', 'SEO & Schema Markup', '60 Days Support'],
      includedArchitecture: ['Next.js 15', 'Sanity CMS', 'Tailwind CSS', 'Vercel'],
    },
    {
      id: 'plan-webdev-advanced-intl',
      slug: 'web-development-advanced-intl',
      name: 'Advanced',
      category: 'Web Development',
      market: 'international',
      startingPrice: 3350,
      startingPriceInr: 249999,
      startingPriceUsd: 3350,
      currency: 'USD',
      currencySymbol: '$',
      billingType: 'ONE_TIME',
      popular: false,
      tagline: 'Established businesses & complex digital websites',
      bestFor: 'Established businesses & complex digital websites',
      targetAudience: 'Established businesses & complex digital websites',
      recommendedFor: 'Established brands needing bespoke dashboards, client portals, search/filter catalogs, and API backends',
      estimatedScope: 'Up to 25 pages, custom dashboards, auth, database, and API integrations.',
      typicalDuration: '4 to 6 Weeks',
      supportDuration: '90 days support',
      ctaLabel: 'Get a Quote',
      depositPercentage: 50,
      features: [
        'Up to 25 pages / flexible architecture',
        'Fully custom UI/UX',
        'Advanced CMS',
        'User authentication',
        'Custom dashboards',
        'API integrations',
        'Third-party service integrations',
        'Advanced SEO architecture',
        'Dynamic content management',
        'Search & filtering',
        'Database integration',
        'Performance optimization',
        'Security hardening',
        'Analytics & conversion tracking',
        'Deployment & production configuration',
        '90 days support',
      ],
      deliverables: ['25 Pages & Portals', 'User Auth & Dashboard', 'Database & APIs', '90 Days Support'],
      includedArchitecture: ['Next.js 15', 'PostgreSQL', 'Auth.js', 'Tailwind CSS'],
    },
    {
      id: 'plan-webdev-enterprise-intl',
      slug: 'web-development-enterprise-intl',
      name: 'Enterprise',
      category: 'Web Development',
      market: 'international',
      startingPrice: 11000,
      startingPriceInr: 829999,
      startingPriceUsd: 11000,
      isStartingFromPlus: true,
      currency: 'USD',
      currencySymbol: '$',
      billingType: 'ONE_TIME',
      popular: false,
      tagline: 'Enterprise organizations & large-scale platforms',
      bestFor: 'Enterprise organizations & large-scale platforms',
      targetAudience: 'Enterprise organizations & large-scale platforms',
      recommendedFor: 'Large enterprise platforms demanding custom design systems, RBAC, high-availability architecture, and IaC handover',
      estimatedScope: 'Enterprise architecture, custom design system, multi-role RBAC, real-time services, cloud deployment, and full Git repository handover.',
      typicalDuration: '8 to 12 Weeks',
      supportDuration: '90 days warranty/support',
      ctaLabel: 'Talk to an Expert',
      depositPercentage: 40,
      features: [
        'Enterprise-grade architecture',
        'Custom design system',
        'Advanced admin dashboard',
        'Multi-role / RBAC access',
        'Custom backend services',
        'Multiple API integrations',
        'Real-time functionality',
        'Advanced search & filtering',
        'Scalable database architecture',
        'Cloud deployment',
        'CI/CD pipeline',
        'Security & performance engineering',
        'Monitoring & logging',
        'High-availability architecture',
        'Technical documentation',
        'Git repository handover',
        '90 days warranty/support',
      ],
      deliverables: ['Enterprise Architecture', 'Multi-Role RBAC', 'Cloud CI/CD', '90 Days Warranty'],
      includedArchitecture: ['Next.js Enterprise', 'PostgreSQL / Cloud SQL', 'Kubernetes', 'Terraform'],
    },
  ],
};

export const DUAL_MARKET_AMC_PLANS: DualMarketPricingConfig = {
  india: [
    {
      id: 'amc-standard-in',
      slug: 'standard-amc',
      name: 'Website Maintenance & Security AMC',
      category: 'Maintenance & AMC',
      market: 'india',
      startingPrice: 7999,
      startingPriceInr: 7999,
      startingPriceUsd: 99,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'MONTHLY',
      popular: false,
      tagline: 'Continuous Uptime, Security Patches & Health Checks',
      bestFor: 'Live websites and portals requiring steady uptime and peace of mind',
      targetAudience: 'Indian businesses & live portals requiring reliable uptime',
      recommendedFor: 'Live websites and portals requiring steady uptime and peace of mind',
      estimatedScope: 'Weekly dependency upgrades, automated daily backups, 24/7 uptime monitoring, security vulnerability patches, 5 hours monthly development.',
      typicalDuration: 'Monthly / Annual Contract',
      supportDuration: 'Continuous Monthly Support',
      ctaLabel: 'Activate Retainer',
      depositPercentage: 100,
      deliverables: [
        '24/7 Automated Uptime & SSL Certificate Monitoring',
        'Daily Automated Offsite Database & File Backups',
        'Security Vulnerability Patching & Framework Updates',
        '5 Hours Dedicated Monthly Feature Tweaks',
        'Monthly Performance & SEO Health Report',
        'Priority Channel Support',
      ],
      features: [
        '99.9% Uptime SLA Monitoring',
        'Emergency Incident Response (< 4 hours)',
        'SEO Health Audits & Broken Link Fixes',
        'Database Vacuuming & Index Optimization',
        'Rollover Hours (Up to 10 hours)',
      ],
      includedArchitecture: ['Sentry Monitoring', 'UptimeRobot', 'GitHub Actions', 'AWS S3 Backups'],
    },
    {
      id: 'amc-cloud-devops-in',
      slug: 'cloud-hosting-devops',
      name: 'Cloud Hosting & DevOps Support',
      category: 'Maintenance & AMC',
      market: 'india',
      startingPrice: 14999,
      startingPriceInr: 14999,
      startingPriceUsd: 199,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'MONTHLY',
      popular: true,
      badgeText: 'MOST POPULAR',
      tagline: 'Cloud Infrastructure Management & Performance Scaling',
      bestFor: 'Growing applications with cloud databases, background jobs and high traffic',
      targetAudience: 'Growing Indian applications with cloud databases and background jobs',
      recommendedFor: 'Growing applications with cloud databases, background jobs and high traffic',
      estimatedScope: 'AWS / GCP / Cloud Run infrastructure oversight, container management, CI/CD pipeline maintenance, database tuning, 10 hours monthly engineering.',
      typicalDuration: 'Monthly / Annual Contract',
      supportDuration: 'Continuous Monthly Support',
      ctaLabel: 'Activate Retainer',
      depositPercentage: 100,
      deliverables: [
        'Cloud Infrastructure Oversight (GCP, AWS, Vercel, Supabase)',
        'CI/CD Pipeline Automation & Deployment Optimization',
        'Database Performance Tuning & Read-Replica Monitoring',
        '10 Hours Monthly DevOps & Infrastructure Engineering',
        'Cloud Cost Optimization Audits',
        '1-Hour Critical Incident Response SLA',
      ],
      features: [
        'Auto-Scaling & Load Balancing Tuning',
        'SSL & DNS Routing Management (Cloudflare)',
        'Disaster Recovery Failover Drills',
        'Docker Container Security Audits',
        'Dedicated WhatsApp VIP Hotline',
      ],
      includedArchitecture: ['Terraform', 'Docker', 'Google Cloud Platform', 'AWS', 'Cloudflare'],
    },
    {
      id: 'amc-dedicated-retainer-in',
      slug: 'dedicated-engineering-retainer',
      name: 'Dedicated Engineering Retainer (40h/mo)',
      category: 'Maintenance & AMC',
      market: 'india',
      startingPrice: 44999,
      startingPriceInr: 44999,
      startingPriceUsd: 599,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'MONTHLY',
      popular: false,
      tagline: 'Your Fractional Senior Tech Team on Demand',
      bestFor: 'Funded startups & enterprises needing continuous sprint execution without hiring overhead',
      targetAudience: 'Funded Indian startups & enterprises needing continuous sprint execution',
      recommendedFor: 'Funded startups & enterprises needing continuous sprint execution without hiring overhead',
      estimatedScope: '40 dedicated hours per month of senior full-stack development, code reviews, feature rollouts, bi-weekly demo sprints, and strategic roadmap consulting.',
      typicalDuration: 'Monthly Sprint Commitment',
      supportDuration: 'Continuous Monthly Sprints',
      ctaLabel: 'Activate Retainer',
      depositPercentage: 100,
      deliverables: [
        '40 Dedicated Hours / Month of Senior Full-Stack Engineering',
        'Direct Senior Architect Assignment & Standup Syncs',
        'Continuous Feature Development & Product Backlog Execution',
        'Bi-Weekly Sprint Releases & Staging Previews',
        'Architecture Advisory & Technical Guidance',
        'Zero Payroll Overhead (No employee taxes or benefits)',
      ],
      features: [
        'Full-Stack Next.js, React, Node.js, Python, Mobile',
        'Guaranteed Monthly Sprint Capacity',
        'Transparent Time-Tracking Logs',
        'Priority 24h Turnaround SLA',
        'Direct GitHub Pull Request Workflows',
      ],
      includedArchitecture: ['Full Next.js Ecosystem', 'Prisma', 'React Native', 'PostgreSQL', 'Gemini AI'],
    },
  ],

  international: [
    {
      id: 'amc-standard-intl',
      slug: 'standard-amc-intl',
      name: 'Standard Maintenance & Security SLA',
      category: 'Maintenance & AMC',
      market: 'international',
      startingPrice: 499,
      startingPriceInr: 41500,
      startingPriceUsd: 499,
      currency: 'USD',
      currencySymbol: '$',
      billingType: 'MONTHLY',
      popular: false,
      tagline: '24/7 Global Uptime, Security Hardening & Continuous Backups',
      bestFor: 'Production websites requiring guaranteed 99.9% uptime and security monitoring',
      targetAudience: 'US & Global companies with live web platforms',
      recommendedFor: 'Production websites requiring guaranteed 99.9% uptime, security monitoring, and regular dependency updates',
      estimatedScope: 'Automated 24/7 monitoring, daily offsite snapshots, dependency security patches, 5 hours monthly development.',
      typicalDuration: 'Monthly / Annual Contract',
      supportDuration: 'Continuous Monthly Support',
      ctaLabel: 'Activate Retainer',
      depositPercentage: 100,
      deliverables: [
        '24/7 Automated Global Uptime & SSL Monitoring',
        'Daily Encrypted Offsite Database & Asset Backups',
        'Security Patching & Framework Upgrades',
        '5 Hours Dedicated Monthly Engineering',
        'Monthly Performance & Core Web Vitals Audits',
        'Slack Channel & Priority Support',
      ],
      features: [
        '99.9% Uptime Guarantee SLA',
        '< 2-Hour Critical Incident Response Window',
        'SEO Health Audits & Broken Link Remediation',
        'Database Vacuuming & Query Performance Optimization',
        'Unused Hours Rollover (Up to 10 hours)',
      ],
      includedArchitecture: ['Sentry APM', 'Datadog', 'GitHub Actions', 'AWS S3 Glacier'],
    },
  ],
};

// Default flat export for backward compatibility
export const CORE_PRICING_PLANS: PricingPlan[] = [
  ...DUAL_MARKET_CORE_PLANS.india,
  ...DUAL_MARKET_CORE_PLANS.international,
];

export const RECURRING_AMC_PLANS: PricingPlan[] = [
  ...DUAL_MARKET_AMC_PLANS.india,
  ...DUAL_MARKET_AMC_PLANS.international,
];

export function getCorePricingPlans(market: PricingMarket = 'india'): PricingPlan[] {
  return DUAL_MARKET_CORE_PLANS[market] || DUAL_MARKET_CORE_PLANS.india;
}

export function getCorePlansByCategory(category: PricingCategory, market: PricingMarket = 'india'): PricingPlan[] {
  const plans = getCorePricingPlans(market);
  return plans.filter((p) => p.category === category);
}

export function getAmcPlans(market: PricingMarket = 'india'): PricingPlan[] {
  return DUAL_MARKET_AMC_PLANS[market] || DUAL_MARKET_AMC_PLANS.india;
}

export function findPlanById(idOrSlug: string, market?: PricingMarket): PricingPlan | undefined {
  const all = [...CORE_PRICING_PLANS, ...RECURRING_AMC_PLANS];
  if (market) {
    const marketMatch = all.find((p) => (p.id === idOrSlug || p.slug === idOrSlug) && p.market === market);
    if (marketMatch) return marketMatch;
  }
  return all.find((p) => p.id === idOrSlug || p.slug === idOrSlug);
}

export const PROMO_COUPONS: Coupon[] = [
  {
    id: 'cpn-welcome10',
    code: 'WELCOME10',
    discountType: 'PERCENTAGE',
    discountValue: 10,
    minOrderValue: 20000,
    maxDiscount: 15000,
    expiresAt: '2026-12-31T23:59:59Z',
    usageLimit: 100,
    usedCount: 14,
    isActive: true,
    description: '10% Launch Discount on any project plan (Up to ₹15,000 / $200 off)',
  },
  {
    id: 'cpn-earlybird',
    code: 'EARLYBIRD',
    discountType: 'FIXED',
    discountValue: 5000,
    minOrderValue: 45000,
    expiresAt: '2026-12-31T23:59:59Z',
    usageLimit: 50,
    usedCount: 9,
    isActive: true,
    description: '₹5,000 Instant Discount on E-Commerce, Mobile App or AI plans',
  },
  {
    id: 'cpn-enterprise20',
    code: 'ENTERPRISE20',
    discountType: 'PERCENTAGE',
    discountValue: 20,
    minOrderValue: 100000,
    maxDiscount: 40000,
    expiresAt: '2026-12-31T23:59:59Z',
    usageLimit: 20,
    usedCount: 3,
    isActive: true,
    description: '20% Special Enterprise Incentive (Up to ₹40,000 off)',
  },
  {
    id: 'cpn-amcstart',
    code: 'AMCSTART',
    discountType: 'FIXED',
    discountValue: 2000,
    minOrderValue: 7000,
    expiresAt: '2026-12-31T23:59:59Z',
    usageLimit: 200,
    usedCount: 22,
    isActive: true,
    description: '₹2,000 Discount on first month AMC engagement',
  },
];

export const DEMO_SAMPLE_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 'sub-brc-8901',
    customerId: 'cust-demo-1',
    customerName: 'Aarav Sharma',
    customerEmail: 'aarav@apexlogistics.in',
    planId: 'amc-standard-in',
    serviceName: 'Website Maintenance & Security AMC',
    billingCycle: 'MONTHLY',
    amountInr: 7999,
    currency: 'INR',
    status: 'ACTIVE',
    currentPeriodStart: '2026-08-01T00:00:00Z',
    currentPeriodEnd: '2026-08-31T23:59:59Z',
    nextRenewalDate: '2026-09-01T00:00:00Z',
    autoRenew: true,
    gracePeriodDays: 5,
    lastPaymentDate: '2026-08-01T10:15:00Z',
    lastRazorpayPaymentId: 'pay_demo_890123',
    createdAt: '2026-05-01T00:00:00Z',
    updatedAt: '2026-08-01T10:15:00Z',
  },
  {
    id: 'sub-brc-8902',
    customerId: 'cust-demo-2',
    customerName: 'Priya Mehra',
    customerEmail: 'priya@zenithretail.com',
    planId: 'amc-cloud-devops-in',
    serviceName: 'Cloud Hosting & DevOps Support',
    billingCycle: 'MONTHLY',
    amountInr: 14999,
    currency: 'INR',
    status: 'ACTIVE',
    currentPeriodStart: '2026-08-15T00:00:00Z',
    currentPeriodEnd: '2026-09-14T23:59:59Z',
    nextRenewalDate: '2026-09-15T00:00:00Z',
    autoRenew: true,
    gracePeriodDays: 5,
    lastPaymentDate: '2026-08-15T14:30:00Z',
    lastRazorpayPaymentId: 'pay_demo_890124',
    createdAt: '2026-06-15T00:00:00Z',
    updatedAt: '2026-08-15T14:30:00Z',
  },
];
