import { PricingPlan, Coupon, Subscription, PricingMarket } from '@/types/payment';

export interface DualMarketPricingConfig {
  india: PricingPlan[];
  international: PricingPlan[];
}

export const DUAL_MARKET_CORE_PLANS: DualMarketPricingConfig = {
  india: [
    {
      id: 'plan-website-in',
      slug: 'website-development',
      name: 'Website Development',
      category: 'Website',
      market: 'india',
      startingPrice: 29999,
      startingPriceInr: 29999,
      startingPriceUsd: 400,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'ONE_TIME',
      popular: false,
      tagline: 'High-Performance Next.js Business Flagship',
      targetAudience: 'Startups, Small Businesses & Growing Indian Brands',
      recommendedFor: 'Founders & businesses seeking high conversion rates, lightning-fast loads, and modern UI',
      estimatedScope: '5 to 10 bespoke pages, responsive UI/UX, headless CMS integration, search engine schema, and 95+ Core Web Vitals.',
      typicalDuration: '2 to 4 Weeks',
      depositPercentage: 50,
      scopeHighlights: [
        'Custom Next.js 15 App Router architecture',
        'Mobile-first responsive design across all viewports',
        'Integrated Headless CMS for non-tech team editing',
        'Google Analytics 4 & Search Console setup',
      ],
      deliverables: [
        'Bespoke Next.js 15 & Tailwind CSS UI (Zero cookie-cutter templates)',
        'Headless Content Management System (Sanity / Strapi / MDX)',
        'Comprehensive On-Page SEO Schema Markup & Lighthouse 95+ Score',
        'Lead Capture Contact Forms with Automated Email Alerts',
        'Complete Git Repository Handover & Production Deployment',
        '30-Day Post-Launch Bug-Fix & Stability Warranty',
      ],
      features: [
        'Sub-second Server-Side Rendered (SSR) Speeds',
        '100% Mobile & Tablet Ergonomic Experience',
        'WCAG AA Accessibility Compliance',
        'Custom Domain & Automated SSL Provisioning',
        'Interactive Tailwind & Motion Micro-Interactions',
        'WhatsApp Business Click-to-Chat & Lead Routing',
      ],
      includedArchitecture: ['Next.js 15', 'TypeScript', 'Tailwind CSS', 'Vercel / Cloud Run', 'Resend / Nodemailer'],
    },
    {
      id: 'plan-ecommerce-in',
      slug: 'ecommerce-development',
      name: 'E-Commerce Development',
      category: 'E-Commerce',
      market: 'india',
      startingPrice: 59999,
      startingPriceInr: 59999,
      startingPriceUsd: 800,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'ONE_TIME',
      popular: true,
      tagline: 'Custom D2C Storefront & High-Velocity Checkout',
      targetAudience: 'D2C Brands, Indian Retailers & Digital Product Sellers',
      recommendedFor: 'Growing merchants needing zero-surcharge storefronts, instant payments, and seamless catalog management',
      estimatedScope: 'Product catalog & variants, instant search/filtering, Razorpay payment gateway integration, inventory ledger, admin order dashboard.',
      typicalDuration: '4 to 6 Weeks',
      depositPercentage: 50,
      scopeHighlights: [
        'Instant search with facet filters & variant selectors',
        'Razorpay Payment Gateway with UPI & Cards integration',
        'Admin inventory, order status & customer management portal',
        'Automated GST-compliant invoice generation',
      ],
      deliverables: [
        'Full-Stack Storefront with Instant Product Filtering & Search',
        'Integrated Razorpay Checkout (UPI, Credit/Debit Cards, NetBanking)',
        'Admin Dashboard for Orders, Stock, Customers & Coupon Management',
        'Automated GST PDF Invoicing & WhatsApp / Email Order Confirmations',
        'PostgreSQL Database Architecture for SKUs, Variants & Stock Ledger',
        '45-Day Post-Launch Technical Support & Staff Handover Training',
      ],
      features: [
        'Blazing Fast Load Times (Zero bloated third-party plugins)',
        'Zero Platform Transaction Fees (You own 100% of your platform)',
        'Abandoned Cart Recovery Email Sequences',
        'Dynamic Coupon & Promotional Discount Engine',
        'Secure Client Authentication & Order Tracking History',
        'Automated Shipping Label & Courier API Readiness',
      ],
      includedArchitecture: ['Next.js App Router', 'PostgreSQL / Prisma', 'Razorpay Gateway', 'Redis Caching', 'Cloudinary / S3'],
    },
    {
      id: 'plan-mobile-app-in',
      slug: 'mobile-app-development',
      name: 'Mobile App Development',
      category: 'Mobile App',
      market: 'india',
      startingPrice: 99999,
      startingPriceInr: 99999,
      startingPriceUsd: 1350,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'ONE_TIME',
      popular: false,
      tagline: 'Cross-Platform iOS & Android Native-Feel Engine',
      targetAudience: 'Tech Startups, Service Platforms & Consumer Brands',
      recommendedFor: 'Companies seeking high mobile engagement, push notifications, and app store deployment',
      estimatedScope: 'Unified React Native / Expo codebase, RESTful backend APIs, biometric auth, push notifications, Play Store & App Store deployment.',
      typicalDuration: '6 to 8 Weeks',
      depositPercentage: 50,
      scopeHighlights: [
        'Single codebase for iOS and Android deployment',
        'Secure token-based backend API with JWT authentication',
        'Push notifications via Firebase Cloud Messaging (FCM)',
        'App Store and Google Play submission assistance',
      ],
      deliverables: [
        'Unified React Native (Expo) Codebase for iOS & Android Devices',
        'Secure Node.js / Express Backend Architecture with JWT Auth',
        'Apple App Store & Google Play Store Submission Assistance',
        'Firebase Cloud Messaging (FCM) Targeted Push Notifications',
        'Biometric Sign-In (Fingerprint / FaceID) & Offline Data Sync',
        '60-Day Post-Launch SLA Warranty & Bug Resolution Support',
      ],
      features: [
        '60fps Fluid Motion & Native Touch Gestures',
        'In-App Payment Gateway & Subscription Capabilities',
        'Real-Time WebSockets & Background Synchronization',
        'Deep Linking & Universal Link Configuration',
        'Camera, Geolocation & Local Device Storage Integration',
        'Sentry & Crashlytics Error Telemetry Instrumentation',
      ],
      includedArchitecture: ['React Native / Expo', 'Node.js / Express', 'PostgreSQL', 'Firebase Auth / FCM', 'Fastlane'],
    },
    {
      id: 'plan-ai-automation-in',
      slug: 'ai-and-automation',
      name: 'AI & Automation',
      category: 'AI & Automation',
      market: 'india',
      startingPrice: 99999,
      startingPriceInr: 99999,
      startingPriceUsd: 1350,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'ONE_TIME',
      popular: false,
      tagline: 'Custom LLM Copilots, Domain RAG & Workflow Automations',
      targetAudience: 'Enterprise Teams, Logistics & Data-Intensive Indian Businesses',
      recommendedFor: 'Organizations aiming to automate manual operations, customer support, and document processing',
      estimatedScope: 'Domain-grounded Retrieval Augmented Generation (RAG), vector database setup (pgvector), multi-modal LLM pipelines, automated webhook triggers.',
      typicalDuration: '4 to 7 Weeks',
      depositPercentage: 50,
      scopeHighlights: [
        'Domain-specific knowledge base with vector embeddings',
        'Streaming LLM chat assistants with token guardrails',
        'Automated document extraction (PDF, Excel, GST Invoices)',
        'Direct CRM / ERP integration pipelines',
      ],
      deliverables: [
        'Domain-Grounded Knowledge Base with Vector Embeddings (pgvector)',
        'Real-Time Streaming Chat Copilot & Multi-Modal Processing',
        'Automated Document Ingestion (PDF, Excel, Scanned Invoices)',
        'Cost-Capped Token Monitoring & Strict Prompt Guardrails',
        'Private Cloud LLM Hosting / Gemini 2.5 & OpenAI API Integration',
        'Architecture Blueprint & Prompt Engineering Runbook',
      ],
      features: [
        'Gemini 2.5 Flash / Pro & GPT-4o Multi-Model Support',
        'Hybrid Semantic & Full-Text Keyword Search',
        'Role-Based Access Control (RBAC) on Knowledge Documents',
        'Audit Logging & Hallucination Prevention Verification',
        'Scheduled Background Job Workers & Alert Triggers',
        'Custom Webhook Integrations with WhatsApp / Slack / Email',
      ],
      includedArchitecture: ['Gemini API SDK', 'pgvector / Supabase', 'Vercel AI SDK', 'BullMQ / Redis', 'Next.js 15'],
    },
    {
      id: 'plan-enterprise-in',
      slug: 'custom-enterprise-solutions',
      name: 'Enterprise Solutions',
      category: 'Custom Enterprise',
      market: 'india',
      startingPrice: 299999,
      startingPriceInr: 299999,
      startingPriceUsd: 4000,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'ONE_TIME',
      popular: false,
      tagline: 'Mission-Critical Cloud Systems, Microservices & Custom Portals',
      targetAudience: 'Scaled Enterprises, FinTech, Logistics & High-Growth SaaS',
      recommendedFor: 'Organizations requiring high concurrency, strict compliance, multi-tenant databases, and dedicated engineering sprints',
      estimatedScope: 'Modular monolith or microservices, distributed relational architecture, audit logging, multi-tenant isolation, legacy modernization.',
      typicalDuration: '8 to 14 Weeks',
      depositPercentage: 40,
      scopeHighlights: [
        'End-to-end scalable enterprise system architecture',
        'Multi-tenant isolation with granular role-based permissions',
        'Automated testing suites (Unit, Integration & E2E)',
        'Full Infrastructure-as-Code (Terraform / Docker) handover',
      ],
      deliverables: [
        'End-to-End Enterprise Architecture & Database Schema Design',
        'Multi-Tenant SaaS Foundation with Role-Based Access Control (RBAC)',
        'Third-Party Integration Suite (ERP, CRM, Payment, Core Banking)',
        'Automated Unit, Integration & End-to-End Test Suite Coverage',
        'OWASP Top 10 Security Audit & Data Privacy Compliance Review',
        '90-Day Priority Enterprise Support & Dedicated Technical Lead',
      ],
      features: [
        'High-Availability Load-Balanced Cloud Infrastructure',
        'Database Partitioning, Index Tuning & Read Replicas',
        'Granular Event Sourcing & Comprehensive Audit Trail',
        'Executive Analytics & Custom Reporting Dashboards',
        'Zero-Downtime Blue/Green Automated CI/CD Deployments',
        'Complete Source Code & Infrastructure-as-Code Ownership',
      ],
      includedArchitecture: ['Next.js Enterprise', 'PostgreSQL / Cloud SQL', 'Docker / Kubernetes', 'Redis Cluster', 'Prisma ORM'],
    },
  ],

  international: [
    {
      id: 'plan-website-intl',
      slug: 'website-development-intl',
      name: 'Website Development',
      category: 'Website',
      market: 'international',
      startingPrice: 2999,
      startingPriceInr: 249000,
      startingPriceUsd: 2999,
      currency: 'USD',
      currencySymbol: '$',
      billingType: 'ONE_TIME',
      popular: false,
      tagline: 'Bespoke Headless Digital Flagship & Conversion Platform',
      targetAudience: 'US & Global Startups, Scale-ups, Digital Agencies & VC-backed Ventures',
      recommendedFor: 'High-growth companies demanding world-class UI engineering, ADA/WCAG compliance, and sub-second global performance',
      estimatedScope: 'Custom design system, headless CMS architecture, dynamic MDX rendering, internationalized SEO metadata, and 98+ Lighthouse scores.',
      typicalDuration: '3 to 4 Weeks',
      depositPercentage: 50,
      scopeHighlights: [
        'US-grade design engineering with custom design tokens',
        'ADA & WCAG 2.1 AA Accessibility standard compliance',
        'Headless CMS setup (Sanity / Contentful / Strapi)',
        'Global CDN caching with sub-second time-to-first-byte',
      ],
      deliverables: [
        'Bespoke Next.js 15 App Router Architecture with Tailwind CSS & Motion',
        'Headless CMS Integration (Sanity / Contentful / Strapi) with Live Preview',
        'Comprehensive International SEO Schema & OpenGraph Social Cards',
        'ADA / WCAG 2.1 AA Accessibility Audit & Compliance Certification',
        'Full GitHub Repository Handover & Multi-Region Vercel/AWS CI/CD Setup',
        '45-Day Post-Launch Priority Warranty & Engineering Support',
      ],
      features: [
        'Sub-800ms Global Page Load Speed on Edge CDNs',
        '100% Fluid Responsive Engineering for 4K to Mobile Viewports',
        'Strict TypeScript Type Safety & Modular Component Library',
        'Custom Domain, DNS Routing & Automated SSL Certificates',
        'Form Automations with Anti-Spam & Webhook Integrations',
        'Full Google Analytics 4, Mixpanel & Tag Manager Architecture',
      ],
      includedArchitecture: ['Next.js 15 (App Router)', 'TypeScript', 'Tailwind CSS', 'Vercel Edge / AWS', 'Sanity / Strapi CMS'],
    },
    {
      id: 'plan-ecommerce-intl',
      slug: 'ecommerce-development-intl',
      name: 'E-Commerce Development',
      category: 'E-Commerce',
      market: 'international',
      startingPrice: 5999,
      startingPriceInr: 498000,
      startingPriceUsd: 5999,
      currency: 'USD',
      currencySymbol: '$',
      billingType: 'ONE_TIME',
      popular: true,
      tagline: 'Custom Headless Commerce & Global Multi-Currency Checkout',
      targetAudience: 'Global D2C Brands, Omnichannel Retailers & SaaS Commerce',
      recommendedFor: 'Businesses needing full control over customer experience, high transaction speed, and zero per-seat platform taxes',
      estimatedScope: 'Bespoke headless storefront, Stripe / PayPal global checkout, multi-currency localization, real-time inventory ledger, custom admin portal.',
      typicalDuration: '5 to 7 Weeks',
      depositPercentage: 50,
      scopeHighlights: [
        'Bespoke headless storefront with sub-second product navigation',
        'Global multi-currency checkout via Stripe / PayPal / Apple Pay',
        'Real-time inventory ledger & automated warehouse webhooks',
        'Automated tax calculations (Stripe Tax / Avalara ready)',
      ],
      deliverables: [
        'Headless Next.js Commerce Storefront with Instant Algolia / Meilisearch Search',
        'Stripe Payments & Elements Checkout (Apple Pay, Google Pay, Multi-Currency)',
        'Custom Merchant Operations Portal for Catalog, Orders, Shipping & Discounts',
        'Automated Transactional Emails & SMS Notifications via Resend / Twilio',
        'Relational Database Modeling (PostgreSQL / Prisma) with Optimistic Locking',
        '60-Day Post-Launch SLA Warranty & Dedicated Engineering Sprints',
      ],
      features: [
        'Zero Revenue Sharing or Transaction Surcharges',
        'Automated Real-Time Tax Calculation Integration',
        'Abandoned Cart Recovery Sequences with Smart Discount Triggers',
        'Customer Account Portal with Order Tracking & Invoice Downloads',
        'High-Concurrency Architecture Built for Peak Flash Sales',
        'Complete Git Codebase & Cloud Deployment Scripts Handover',
      ],
      includedArchitecture: ['Next.js App Router', 'PostgreSQL / Prisma', 'Stripe SDK', 'Redis Caching', 'Cloudinary / S3 CDN'],
    },
    {
      id: 'plan-mobile-app-intl',
      slug: 'mobile-app-development-intl',
      name: 'Mobile App Development',
      category: 'Mobile App',
      market: 'international',
      startingPrice: 9999,
      startingPriceInr: 830000,
      startingPriceUsd: 9999,
      currency: 'USD',
      currencySymbol: '$',
      billingType: 'ONE_TIME',
      popular: false,
      tagline: 'Production-Grade Cross-Platform iOS & Android Native Suite',
      targetAudience: 'Global Consumer Tech, HealthTech, FinTech & Enterprise Mobility',
      recommendedFor: 'Startups & enterprises requiring high-performance mobile apps with strict security and App Store review guarantees',
      estimatedScope: 'Unified React Native / Expo codebase, scalable REST/GraphQL API backend, push notifications, offline SQLite sync, app store submission.',
      typicalDuration: '7 to 10 Weeks',
      depositPercentage: 50,
      scopeHighlights: [
        'Single React Native / Expo codebase with 60fps native feel',
        'Secure microservices backend with OAuth2 & biometric auth',
        'Complete Apple App Store & Google Play submission management',
        'Offline-first architecture with background synchronization',
      ],
      deliverables: [
        'Production React Native (Expo) Codebase for iOS & Android Ecosystems',
        'Scalable Node.js / Go Backend API Architecture with JWT / OAuth2 Auth',
        'Complete App Store Review & Google Play Store Submission Management',
        'Push Notification Engine via Firebase Cloud Messaging & OneSignal',
        'Biometric Security (Face ID / Touch ID) & Offline SQLite Sync Engine',
        '60-Day Post-Launch SLA Warranty & Dedicated Release Engineer',
      ],
      features: [
        '60fps Fluid Gesture Navigation & Haptic Feedback',
        'In-App Subscriptions & Purchases (StoreKit / RevenueCat)',
        'Real-Time WebSockets for Instant Messaging & Live Tracking',
        'Universal Deep Links & Branch.io Attribution Readiness',
        'Full Sensor Integration: Camera, GPS Geofencing, HealthKit',
        'Sentry Error Telemetry & Automated Crash Analytics Setup',
      ],
      includedArchitecture: ['React Native / Expo', 'Node.js / TypeScript', 'PostgreSQL', 'Firebase / OneSignal', 'RevenueCat'],
    },
    {
      id: 'plan-ai-automation-intl',
      slug: 'ai-and-automation-intl',
      name: 'AI & Automation',
      category: 'AI & Automation',
      market: 'international',
      startingPrice: 7999,
      startingPriceInr: 664000,
      startingPriceUsd: 7999,
      currency: 'USD',
      currencySymbol: '$',
      billingType: 'ONE_TIME',
      popular: false,
      tagline: 'Enterprise RAG Architecture, Autonomous AI Agents & Vector Workflows',
      targetAudience: 'US Enterprises, AI-First Startups & Knowledge-Worker Automations',
      recommendedFor: 'Organizations looking to build domain-grounded generative AI products, automate multi-step workflows, and reduce operational overhead',
      estimatedScope: 'Multi-modal Gemini 2.5 / OpenAI / Claude pipelines, vector search (pgvector/Pinecone), document parsing, streaming UI, background workers.',
      typicalDuration: '5 to 8 Weeks',
      depositPercentage: 50,
      scopeHighlights: [
        'Domain-specific RAG architecture with vector database indexing',
        'Autonomous AI agents with tool-calling and retry mechanisms',
        'Multi-format document parsing (PDFs, spreadsheets, contracts)',
        'Strict token budgeting, cost tracking & safety guardrails',
      ],
      deliverables: [
        'Domain-Specific RAG Knowledge Pipeline with Vector Search (pgvector/Pinecone)',
        'Real-Time Streaming Chat Copilot & Multi-Modal Document Analyzer',
        'Automated ETL Extraction Pipelines for Enterprise Knowledge Systems',
        'Cost-Capped Token Monitoring Dashboard & Prompt Guardrail Engine',
        'Secure Cloud API Integration (Gemini 2.5, OpenAI GPT-4o, Anthropic Claude)',
        'Comprehensive Architecture Blueprints & Prompt Engineering Handbook',
      ],
      features: [
        'Multi-LLM Routing & Automatic Fallback Management',
        'Hybrid Semantic Dense & Sparse BM25 Keyword Search',
        'Role-Based Document Permissions (RBAC) & Tenant Isolation',
        'Full Audit Logging & Hallucination Prevention Guardrails',
        'Asynchronous Queue Processing (BullMQ / Celery) for Heavy Workloads',
        'Enterprise Webhook Connectors for Slack, Notion, Hubspot & Salesforce',
      ],
      includedArchitecture: ['Gemini API SDK', 'pgvector / Pinecone', 'LangChain / Vercel AI SDK', 'BullMQ / Redis', 'Next.js 15'],
    },
    {
      id: 'plan-enterprise-intl',
      slug: 'custom-enterprise-solutions-intl',
      name: 'Enterprise Solutions',
      category: 'Custom Enterprise',
      market: 'international',
      startingPrice: 24999,
      startingPriceInr: 2075000,
      startingPriceUsd: 24999,
      currency: 'USD',
      currencySymbol: '$',
      billingType: 'ONE_TIME',
      popular: false,
      tagline: 'Distributed Cloud Systems, High-Concurrency SaaS & Modernization',
      targetAudience: 'Mid-Market & Enterprise Organizations, Scaled Multi-Tenant SaaS',
      recommendedFor: 'Enterprises needing high-availability infrastructure, SOC2/GDPR compliance, legacy system re-architecture, and dedicated engineering sprints',
      estimatedScope: 'Distributed microservices / modular monolith, multi-region database replication, event-driven streaming, compliance audits, 24/7 SLA.',
      typicalDuration: '10 to 16 Weeks',
      depositPercentage: 40,
      scopeHighlights: [
        'Full enterprise architecture design with high-availability load balancing',
        'Multi-tenant database partitioning & horizontal read replicas',
        'SOC2 Type II / GDPR / HIPAA alignment security audits',
        'Dedicated senior tech lead, bi-weekly demos & full IaC scripts',
      ],
      deliverables: [
        'End-to-End Enterprise Architecture Blueprint & Database Schemas',
        'Multi-Tenant SaaS Foundation with Granular Role-Based Access Control',
        'Comprehensive Third-Party Integration Suite (SAP, Salesforce, Stripe, ERP)',
        'Full Automated Testing Pipeline (Unit, Integration & E2E Cypress/Playwright)',
        'SOC2 Type II / GDPR / OWASP Compliance & Threat Modeling Audit',
        '90-Day Priority Enterprise SLA Support with Direct Lead Architect Access',
      ],
      features: [
        'High-Availability Multi-Region Load-Balanced Cloud Infrastructure',
        'Database Partitioning, Query Index Tuning & Automated Failover',
        'Distributed Event-Driven Architecture with Kafka / Redis Streams',
        'Custom Executive Analytics Dashboards & Audit Trail Reports',
        'Zero-Downtime Blue/Green Automated CI/CD Deployments',
        'Full Source Code & Infrastructure-as-Code (Terraform / Docker) Handover',
      ],
      includedArchitecture: ['Next.js Enterprise', 'PostgreSQL / Cloud SQL', 'Docker / Kubernetes', 'Redis Cluster', 'Terraform'],
    },
  ],
};

export const DUAL_MARKET_AMC_PLANS: DualMarketPricingConfig = {
  india: [
    {
      id: 'amc-standard-in',
      slug: 'standard-amc',
      name: 'Website Maintenance & Security AMC',
      category: 'Maintenance & AMC',
      market: 'india',
      startingPrice: 7999,
      startingPriceInr: 7999,
      startingPriceUsd: 99,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'MONTHLY',
      popular: false,
      tagline: 'Continuous Uptime, Security Patches & Health Checks',
      targetAudience: 'Indian businesses & live portals requiring reliable uptime',
      recommendedFor: 'Live websites and portals requiring steady uptime and peace of mind',
      estimatedScope: 'Weekly dependency upgrades, automated daily backups, 24/7 uptime monitoring, security vulnerability patches, 5 hours monthly development.',
      typicalDuration: 'Monthly / Annual Contract',
      depositPercentage: 100,
      deliverables: [
        '24/7 Automated Uptime & SSL Certificate Monitoring',
        'Daily Automated Offsite Database & File Backups',
        'Security Vulnerability Patching & Framework Dependency Updates',
        '5 Hours Dedicated Monthly Feature Tweaks & Content Updates',
        'Monthly Performance, SEO & Analytics Health Report',
        'Priority Email & WhatsApp Channel Support',
      ],
      features: [
        '99.9% Uptime SLA Monitoring',
        'Emergency Incident Response (< 4 hours)',
        'SEO Health Audits & Broken Link Fixes',
        'Database Vacuuming & Index Optimization',
        'Rollover Hours (Up to 10 hours)',
      ],
      includedArchitecture: ['Sentry Monitoring', 'UptimeRobot', 'GitHub Actions', 'AWS S3 Backups'],
    },
    {
      id: 'amc-cloud-devops-in',
      slug: 'cloud-hosting-devops',
      name: 'Cloud Hosting & DevOps Support',
      category: 'Maintenance & AMC',
      market: 'india',
      startingPrice: 14999,
      startingPriceInr: 14999,
      startingPriceUsd: 199,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'MONTHLY',
      popular: true,
      tagline: 'Cloud Infrastructure Management & Performance Scaling',
      targetAudience: 'Growing Indian applications with cloud databases and background jobs',
      recommendedFor: 'Growing applications with cloud databases, background jobs and high traffic',
      estimatedScope: 'AWS / GCP / Cloud Run infrastructure oversight, container management, CI/CD pipeline maintenance, database tuning, 10 hours monthly engineering.',
      typicalDuration: 'Monthly / Annual Contract',
      depositPercentage: 100,
      deliverables: [
        'Cloud Infrastructure Oversight (GCP, AWS, Vercel, Supabase)',
        'CI/CD Pipeline Automation & Deployment Optimization',
        'Database Performance Tuning & Read-Replica Monitoring',
        '10 Hours Monthly DevOps & Infrastructure Engineering',
        'Cloud Cost Optimization Audits (Reducing monthly bills)',
        '1-Hour Critical Incident Response SLA',
      ],
      features: [
        'Auto-Scaling & Load Balancing Tuning',
        'SSL & DNS Routing Management (Cloudflare)',
        'Disaster Recovery Failover Drills',
        'Docker Container Security Audits',
        'Dedicated WhatsApp VIP Hotline',
      ],
      includedArchitecture: ['Terraform', 'Docker', 'Google Cloud Platform', 'AWS', 'Cloudflare'],
    },
    {
      id: 'amc-dedicated-retainer-in',
      slug: 'dedicated-engineering-retainer',
      name: 'Dedicated Engineering Retainer (40h/mo)',
      category: 'Maintenance & AMC',
      market: 'india',
      startingPrice: 44999,
      startingPriceInr: 44999,
      startingPriceUsd: 599,
      currency: 'INR',
      currencySymbol: '₹',
      billingType: 'MONTHLY',
      popular: false,
      tagline: 'Your Fractional Senior Tech Team on Demand',
      targetAudience: 'Funded Indian startups & enterprises needing continuous sprint execution',
      recommendedFor: 'Funded startups & enterprises needing continuous sprint execution without hiring overhead',
      estimatedScope: '40 dedicated hours per month of senior full-stack development, code reviews, feature rollouts, bi-weekly demo sprints, and strategic roadmap consulting.',
      typicalDuration: 'Monthly Sprint Commitment',
      depositPercentage: 100,
      deliverables: [
        '40 Dedicated Hours / Month of Senior Full-Stack Engineering',
        'Direct Senior Architect Assignment & Standup Syncs',
        'Continuous Feature Development & Product Backlog Execution',
        'Bi-Weekly Sprint Releases & Staging Previews',
        'Architecture Advisory & Technical Hiring Guidance',
        'Zero Payroll Overhead (No employee taxes, benefits, or hardware costs)',
      ],
      features: [
        'Full-Stack Next.js, React, Node.js, Python, Mobile',
        'Guaranteed Monthly Sprint Capacity',
        'Transparent Time-Tracking Logs',
        'Priority 24h Turnaround SLA',
        'Direct GitHub Pull Request Workflows',
      ],
      includedArchitecture: ['Full Next.js Ecosystem', 'Prisma', 'React Native', 'PostgreSQL', 'Gemini AI'],
    },
  ],

  international: [
    {
      id: 'amc-standard-intl',
      slug: 'standard-amc-intl',
      name: 'Standard Maintenance & Security SLA',
      category: 'Maintenance & AMC',
      market: 'international',
      startingPrice: 499,
      startingPriceInr: 41500,
      startingPriceUsd: 499,
      currency: 'USD',
      currencySymbol: '$',
      billingType: 'MONTHLY',
      popular: false,
      tagline: '24/7 Global Uptime, Security Hardening & Continuous Backups',
      targetAudience: 'US & Global companies with live web platforms',
      recommendedFor: 'Production websites requiring guaranteed 99.9% uptime, security monitoring, and regular dependency updates',
      estimatedScope: 'Automated 24/7 monitoring, daily offsite snapshots, dependency security patches, 5 hours monthly development.',
      typicalDuration: 'Monthly / Annual Contract',
      depositPercentage: 100,
      deliverables: [
        '24/7 Automated Global Uptime & SSL Monitoring',
        'Daily Encrypted Offsite Database & Asset Backups',
        'Security Vulnerability Patching & NPM/Node Dependency Upgrades',
        '5 Hours Dedicated Monthly Engineering & UI Enhancements',
        'Monthly Performance, Lighthouse & Core Web Vitals Audits',
        'Dedicated Slack Connect Channel & Priority Email Support',
      ],
      features: [
        '99.9% Uptime Guarantee SLA',
        '< 2-Hour Critical Incident Response Window',
        'SEO Health Audits & Broken Link Remediation',
        'Database Vacuuming & Query Performance Optimization',
        'Unused Hours Rollover (Up to 10 hours)',
      ],
      includedArchitecture: ['Sentry APM', 'Datadog / BetterStack', 'GitHub Actions', 'AWS S3 Glacier'],
    },
    {
      id: 'amc-cloud-devops-intl',
      slug: 'cloud-hosting-devops-intl',
      name: 'Cloud Infrastructure & DevOps Support',
      category: 'Maintenance & AMC',
      market: 'international',
      startingPrice: 1299,
      startingPriceInr: 108000,
      startingPriceUsd: 1299,
      currency: 'USD',
      currencySymbol: '$',
      billingType: 'MONTHLY',
      popular: true,
      tagline: 'Multi-Cloud Orchestration, Cost Optimization & SRE SLA',
      targetAudience: 'US & Global SaaS companies with high-throughput cloud environments',
      recommendedFor: 'Growing applications with multi-region databases, background queues, and high traffic requiring SRE reliability',
      estimatedScope: 'AWS / GCP / Cloud Run infrastructure oversight, container management, CI/CD pipeline maintenance, database tuning, 12 hours monthly engineering.',
      typicalDuration: 'Monthly / Annual Contract',
      depositPercentage: 100,
      deliverables: [
        'Cloud Infrastructure & Container Management (GCP, AWS, Vercel, Supabase)',
        'CI/CD Pipeline Automation & Deployment Acceleration',
        'Database Performance Tuning & Read-Replica Monitoring',
        '12 Hours Monthly DevOps & Site Reliability Engineering',
        'Cloud Cost Optimization Audits (Targeting 20–40% AWS/GCP bill reductions)',
        '30-Minute Critical Incident Response SLA',
      ],
      features: [
        'Auto-Scaling & Load Balancing Tuning',
        'Enterprise WAF, SSL & DDoS Protection (Cloudflare Enterprise)',
        'Disaster Recovery & Multi-Region Failover Drills',
        'Docker & Kubernetes Container Security Audits',
        'Dedicated Slack Connect VIP Channel with US Time-Zone Overlap',
      ],
      includedArchitecture: ['Terraform', 'Docker / Kubernetes', 'Google Cloud Platform', 'AWS', 'Cloudflare'],
    },
    {
      id: 'amc-dedicated-retainer-intl',
      slug: 'dedicated-engineering-retainer-intl',
      name: 'Dedicated Engineering Retainer (40h/mo)',
      category: 'Maintenance & AMC',
      market: 'international',
      startingPrice: 3499,
      startingPriceInr: 290000,
      startingPriceUsd: 3499,
      currency: 'USD',
      currencySymbol: '$',
      billingType: 'MONTHLY',
      popular: false,
      tagline: 'Your Fractional Senior Tech Team on Demand',
      targetAudience: 'Funded US & International startups & tech teams',
      recommendedFor: 'Funded startups & tech teams seeking senior full-stack execution without high Silicon Valley recruiter fees',
      estimatedScope: '40 dedicated hours per month of senior full-stack engineering, code reviews, bi-weekly sprint demos, and strategic architecture advisory.',
      typicalDuration: 'Monthly Sprint Commitment',
      depositPercentage: 100,
      deliverables: [
        '40 Dedicated Hours / Month of Senior Engineering (Next.js, Node.js, AI)',
        'Direct Senior Architect Assignment with Daily Async & Weekly Video Standups',
        'Continuous Feature Development, Backlog Grooming & Refactoring',
        'Bi-Weekly Sprint Releases & Staging Previews',
        'System Architecture Advisory & Technical Due Diligence Guidance',
        'Zero Overhead (No payroll taxes, medical benefits, or long-term lock-in)',
      ],
      features: [
        'Full-Stack TypeScript, React, Next.js, Python & Mobile Development',
        'Guaranteed Monthly Sprint Velocity & Capacity Allocation',
        'Detailed Time-Tracking & Pull Request Transparency',
        'Priority 24-Hour Turnaround SLA',
        'Seamless Integration with your Jira, Linear, or GitHub Projects',
      ],
      includedArchitecture: ['Full Next.js Ecosystem', 'Prisma', 'React Native', 'PostgreSQL', 'Gemini AI'],
    },
  ],
};

// Default flat export for backward compatibility
export const CORE_PRICING_PLANS: PricingPlan[] = [
  ...DUAL_MARKET_CORE_PLANS.india,
  ...DUAL_MARKET_CORE_PLANS.international,
];

export const RECURRING_AMC_PLANS: PricingPlan[] = [
  ...DUAL_MARKET_AMC_PLANS.india,
  ...DUAL_MARKET_AMC_PLANS.international,
];

export function getCorePricingPlans(market: PricingMarket = 'india'): PricingPlan[] {
  return DUAL_MARKET_CORE_PLANS[market] || DUAL_MARKET_CORE_PLANS.india;
}

export function getAmcPlans(market: PricingMarket = 'india'): PricingPlan[] {
  return DUAL_MARKET_AMC_PLANS[market] || DUAL_MARKET_AMC_PLANS.india;
}

export function findPlanById(idOrSlug: string, market?: PricingMarket): PricingPlan | undefined {
  const all = [...CORE_PRICING_PLANS, ...RECURRING_AMC_PLANS];
  if (market) {
    const marketMatch = all.find((p) => (p.id === idOrSlug || p.slug === idOrSlug) && p.market === market);
    if (marketMatch) return marketMatch;
  }
  return all.find((p) => p.id === idOrSlug || p.slug === idOrSlug);
}

export const PROMO_COUPONS: Coupon[] = [
  {
    id: 'cpn-welcome10',
    code: 'WELCOME10',
    discountType: 'PERCENTAGE',
    discountValue: 10,
    minOrderValue: 20000,
    maxDiscount: 15000,
    expiresAt: '2026-12-31T23:59:59Z',
    usageLimit: 100,
    usedCount: 14,
    isActive: true,
    description: '10% Launch Discount on any project plan (Up to ₹15,000 / $200 off)',
  },
  {
    id: 'cpn-earlybird',
    code: 'EARLYBIRD',
    discountType: 'FIXED',
    discountValue: 5000,
    minOrderValue: 45000,
    expiresAt: '2026-12-31T23:59:59Z',
    usageLimit: 50,
    usedCount: 9,
    isActive: true,
    description: '₹5,000 Instant Discount on E-Commerce, Mobile App or AI plans',
  },
  {
    id: 'cpn-enterprise20',
    code: 'ENTERPRISE20',
    discountType: 'PERCENTAGE',
    discountValue: 20,
    minOrderValue: 100000,
    maxDiscount: 40000,
    expiresAt: '2026-12-31T23:59:59Z',
    usageLimit: 20,
    usedCount: 3,
    isActive: true,
    description: '20% Special Enterprise Incentive (Up to ₹40,000 off)',
  },
  {
    id: 'cpn-amcstart',
    code: 'AMCSTART',
    discountType: 'FIXED',
    discountValue: 2000,
    minOrderValue: 7000,
    expiresAt: '2026-12-31T23:59:59Z',
    usageLimit: 200,
    usedCount: 22,
    isActive: true,
    description: '₹2,000 Discount on first month AMC engagement',
  },
];

export const DEMO_SAMPLE_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 'sub-brc-8901',
    customerId: 'cust-demo-1',
    customerName: 'Aarav Sharma',
    customerEmail: 'aarav@apexlogistics.in',
    planId: 'amc-standard-in',
    serviceName: 'Website Maintenance & Security AMC',
    billingCycle: 'MONTHLY',
    amountInr: 7999,
    currency: 'INR',
    status: 'ACTIVE',
    currentPeriodStart: '2026-08-01T00:00:00Z',
    currentPeriodEnd: '2026-08-31T23:59:59Z',
    nextRenewalDate: '2026-09-01T00:00:00Z',
    autoRenew: true,
    gracePeriodDays: 5,
    lastPaymentDate: '2026-08-01T10:15:00Z',
    lastRazorpayPaymentId: 'pay_demo_890123',
    createdAt: '2026-05-01T00:00:00Z',
    updatedAt: '2026-08-01T10:15:00Z',
  },
  {
    id: 'sub-brc-8902',
    customerId: 'cust-demo-2',
    customerName: 'Priya Mehra',
    customerEmail: 'priya@zenithretail.com',
    planId: 'amc-cloud-devops-in',
    serviceName: 'Cloud Hosting & DevOps Support',
    billingCycle: 'MONTHLY',
    amountInr: 14999,
    currency: 'INR',
    status: 'ACTIVE',
    currentPeriodStart: '2026-08-15T00:00:00Z',
    currentPeriodEnd: '2026-09-14T23:59:59Z',
    nextRenewalDate: '2026-09-15T00:00:00Z',
    autoRenew: true,
    gracePeriodDays: 5,
    lastPaymentDate: '2026-08-15T14:30:00Z',
    lastRazorpayPaymentId: 'pay_demo_890124',
    createdAt: '2026-06-15T00:00:00Z',
    updatedAt: '2026-08-15T14:30:00Z',
  },
];
